### PR TITLE
Journald

### PR DESCRIPTION
**Pull request by nikicat**
This PR adds support for logging via journald on Linux.

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
NACK for adding new npm dependencies

**Comment by nikicat** [comment]
> NACK for adding new npm dependencies

Is it bad? Why? Is it some kind of project policy?

**Comment by wiz** [comment]
Yeah we're trying to remove npm deps, not add more

**Comment by nikicat** [comment]
So how this or a similar feature should be implemented? By vendoring 3rd party lib or other way? Are there some written policies about it?

**Comment by wiz** [comment]
Yeah sorry, if you can implement it without using third party npm deps then please make a new PR

**Pull request closed without merging**
