### PR TITLE
Change mempool project license to GNU Affero General Public License v3

### PR DESCRIPTION
**Pull request by wiz**
The files contained in this source code repository are currently released as "open source" under the terms of the [MIT license](https://opensource.org/licenses/MIT), with the additional protections of the [Commons Clause License Condition v1](https://commonsclause.com/), in order to restrict monetization of the mempool app, with the intended result of mempool remaining free software (as in free beer) for the Bitcoin community.

However, because of the Commons Clause being added to our license terms, The Mempool Open Source Project cannot formally be considered as [Free and open-source software (FOSS)](https://en.wikipedia.org/wiki/Free_and_open-source_software), according to the generally accepted definition of ["What is free software?"](https://www.gnu.org/philosophy/free-sw.en.html), and this has drawn some criticism from the Bitcoin open source community.

Therefore, in order to make The Mempool Open Source Project truly FOSS, I hereby propose to change our project's license to the [GNU Affero General Public License v3](https://www.gnu.org/licenses/agpl-3.0.html), which seems most suitable for a web application. While this won't keep the mempool free as in free beer, it will keep mempool free as in free speech, which is what actually matters.

Here is [the TL;DR of AGPLv3](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)):
> The AGPL license differs from the other GNU licenses in that it was
> built for network software. You can distribute modified versions if
> you keep track of the changes and the date you made them. As per usual
> with GNU licenses, you must license derivatives under AGPL. It
> provides the same restrictions and freedoms as the GPLv3 but with an
> additional clause which makes it so that source code must be
> distributed along with web publication. Since web sites and services
> are never distributed in the traditional sense, the AGPL is the GPL of
> the web.

If there are no objections, could all contributors to The Mempool Open Source Project please ACK this PR?
@softsimon @wiz @bguillaumat @TechMiX @junderw @andrerfneves @pox @jambolo @6102bitcoin @devinbileck @fiatjaf @timlucmiptev @Czino @lucasmoten

### CODE REVIEW

**Comment by softsimon** [comment]
ACK

**Comment by bguillaumat** [comment]
ACK

**Comment by TechMiX** [comment]
ACK

**Comment by fiatjaf** [comment]
ACK

**Comment by devinbileck** [comment]
ACK

**Comment by junderw** [comment]
ACK

**Comment by 6102bitcoin** [comment]
ACK

**Comment by wiz** [comment]
Thanks for the fast responses! It looks like everyone who contributed actual code has ACK'd this PR, and there being no objections I'll go ahead and merge this. Also I'll add the new AGPLv3 license notice to the bottom of our mempool.space/about page to make the new license terms more prominently displayed.

**Comment by andrerfneves** [comment]
ACK

**Comment by rbrooklyn** [comment]
ACK

**Comment by pox** [comment]
ACK

**Comment by hsjoberg** [comment]
ACK

**Pull request merged**
