### PR TITLE
Fix mempool-graph legend off-by-one

### PR DESCRIPTION
**Pull request by jambolo**
Resolves issue #190 as noted.

### CODE REVIEW

**Comment by jambolo** [comment]
Note that the commit message lists the wrong issue number.

**Comment by junderw** [comment]
This only fixes the color issue by virtue of lowering the legend count to 26.

This is not off-by-one, but rather modulo constraint mismatch.

Currently mempool sets 26 classes for dynamic legend css classes, a through z.

There are 27 legends. so index 26 (the 27th one) is modulo 26, which 26 % 26 is 0, so the css class for `a` (aka the first one, currently 1 sat/vB) is used for the last legend.

However, I worry about the treatment of the 1 sat/vB data. Currently bitcoin is showing 45 MvB @ 1sat/vB (the legend you're removing) and 15 MvB @ 1 - 2... I wonder if the data will shift over 1 so that `1 - 2` will now say 45 MvB with this change even though it's not correct.

The issue of the wrapping class names still exists for Liquid...

So if 45 MvB is actually for 1 - 2 and not 1... and 15 MvB (currently 1 - 2) is actually 2 - 3 then this is a o-b-o bug... but the legend coloring bug still exists.

---

1. We need to check that this fix is actually fixing a data shift of some kind (where the wrong data is in the wrong legend) if we were to merge as is.
2. The legend coloring issue will still remain for liquid if so.

**Comment by junderw** [comment]
スクリーンショット_2021-03-06_00-21-05

**Comment by junderw** [comment]
Here's the list of series names... I tried adding `aa` to this list but it didn't fix it.

https://github.com/mempool/mempool/blob/v2.1.2/frontend/src/styles.scss#L209

**Comment by junderw** [comment]
@wiz can we deploy this to ninja?

**Review by jambolo — COMMENTED** [review]
Note that the commit message lists the wrong issue. I believe that can be fixed when the PR is merged.

**Review by wiz — APPROVED** [review]
ACK - tested OK on node220.bitcoin.wiz.biz/graphs

**Comment by wiz** [comment]
> @wiz can we deploy this to ninja?

actually it's not possible to fully test on .ninja because it only has a 300MB so I deployed to node220 which has a larger mempool which contains 1 sat/vB transactions - looks good

**Pull request merged**
