### PR TITLE
Index coinstatsindex - Add bulk block query api

### PR DESCRIPTION
**Pull request by nymkappa**
### TODO before this PR is complete:

- [x] `medianFeeAmt`
- [x] `feePercentiles`
- [x] `orphaned` (and maybe provide orphaned block hash if possible)
- [x] ~`blockTime`~ - Will not implement

### Description

This PR indexes new block data gathered from the `getblockstats`, and `gettxoutsetinfo` core RPC command. 

`gettxoutsetinfo` requires `coinstatsindex=1` to be enabled in `bitcoin.conf`. However enabling this index is not required to run mempool, fields will simply be nullified. If in the future the index is enabled and core is done with re-indexing, we will automatically detect it and **update** our database.

The `blocks` table is now 778MB.

The new data is served through a new API endpoint which has been provided to query blocks between two block heights: `/api/v1/blocks-bulk/:minHeight/:maxHeight` with `maxHeight` defaulting to the current tip if not provided.  An example can be found at the end of this PR description.

### Test scenarios

A new configuration setting has been added `config.MEMPOOL.MAX_BLOCKS_BULK_QUERY` which default to `0`. When set to `0` or less, the new `blocks-bulk` API endpoint is disabled.
Set it to any positive number to choose how many blocks can be queries in a single query.

- The feature is Bitcoin only, 404 otherwise
- Mempool nodejs backend indexing must be enabled _(`config.DATABASE.ENABLED` set to `true` and `config.MEMPOOL.INDEXING_BLOCKS_AMOUNT` set to a positive value)_, 404 otherwise
- In core, if `coinstatsindex=0` then `utxoset_size` and `total_input_amt` will be set to `null` in the API response
- In core, if `coinstatsindex=1` and core is currently indexing, `utxoset_size` and `total_input_amt` will be set to `null` in the API response until core is done indexing
- In core, if `coinstatsindex=1` and core finished indexing all blocks, `utxoset_size` and `total_input_amt` will be properly returned
- `fee_amt_percentiles` and `median_fee_amt` requires `config.MEMPOOL.INDEXING_BLOCKS_AMOUNT: true`, `null` otherwise

Example response https://github.com/mempool/mempool/pull/3070#issuecomment-1442721036

### CODE REVIEW

**Comment by sha2fiddy** [comment]
This is looking great, thanks @nymkappa!!

What is meant by the `fee_span`?  Is this the `[0th, 10th, 25th, 50th, 75th, 90th, 100th]` percentiles of `feerates` similar to `fee_percentiles` (absolute fee amounts)?  I am sometimes confused in Core if it a field is meant to represent an absolute fee vs a feerate.  In general, it's nice to have the mean and min/med/max, etc. percentiles for both metrics.

Is it possible to parse out the "tag" aka "miner signature" from the raw coinbase as a separate field?  This would correspond to `poolsJson['coinbase_tags']`.

🚀🚀🚀

**Comment by nymkappa** [comment]
> What is meant by the `fee_span`? Is this the `[0th, 10th, 25th, 50th, 75th, 90th, 100th]` percentiles of `feerates` similar to `fee_percentiles` (absolute fee amounts)? I am sometimes confused in Core if it a field is meant to represent an absolute fee vs a feerate. In general, it's nice to have the mean and min/med/max, etc. percentiles for both metrics.

`fee_span` is our already existing field, representing the fee rates percentiles. The first value is the minimum, and the last value is the maximum. You can get the median fee rate with the 50th value or using the `median_fee` field.

`fee_percentiles` is the same thing but for absolute fee amount in sats, as you correctly guessed. You can get the absolute median fee using the 50th percentiles or using the `median_fee_amt` field.

> Is it possible to parse out the "tag" aka "miner signature" from the raw coinbase as a separate field? This would correspond to `poolsJson['coinbase_tags']`.

Will do.

**Comment by sha2fiddy** [comment]
> `fee_span` is our already existing field, representing the fee rates percentiles ... `fee_percentiles` is the same thing but for absolute fee amount in sats

got it.  I think it would be clearer if all fields representing a `fee` or a `fee_rate` were explicitly labeled as such.

> `"coinbase_signature_ascii": "\u00033Þ\u000b\u0004Qêõc/Foundry USA Pool #dropgold/\u0007ÿý¶Y\u0000\u0000\u0000\u0000\u0000\u0000\u0000"`

Thanks!  Just so I understand, is this how the 'coinbase signature' is passed into Mempool's pool parser?  Or do you first drop all the padded nulls, etc.?  This is how it's displayed in the frontend:

Screenshot 2023-02-23 at 6 48 00 AM

**Comment by wiz** [comment]
please rebase so I can deploy this to a staging server for foundry to test

**Comment by nymkappa** [comment]
> I think it would be clearer if all fields representing a `fee` or a `fee_rate` were explicitly labeled as such.

Right, we just used a bad naming convention in other APIs. But I guess since we're providing a new API that is not used anywhere yet we could properly renamed fields before sending the response. **I'll update**.
 
> Thanks! Just so I understand, is this how the 'coinbase signature' is passed into Mempool's pool parser? Or do you first drop all the padded nulls, etc.? This is how it's displayed in the frontend:

If you check the html, we actually display ` -c/Foundry USA Pool #dropgold/D/? ` which corresponds to the `\u.....` characters you see in the API response. But since the browser does not how to render them he just ignores them.

On mempool.space we use the hex value of the coinbase (`coinbase_raw` field), and parse it using https://github.com/mempool/mempool/blob/master/frontend/src/app/shared/pipes/hex2ascii/hex2ascii.pipe.ts, which results in what I just shared.

**Comment by nymkappa** [comment]
@sha2fiddy here is the updated response format

```
  {
    "height": 778046,
    "hash": "00000000000000000002ce131adf05133d982f206e3fec8d08d370592f00182f",
    "timestamp": 1677204748,
    "median_timestamp": 1677199096,
    "previous_block_hash": "000000000000000000024349bf0853052557f634db4aad1b24778f7205d6ae00",
    "difficulty": 39156400059293.19,
    "header": "0000c52200aed605728f77241bad4adb34f65725055308bf4943020000000000000000007ee256155bebe2a660e941478447ec93180e9c1b36c31617645d2e3de54062650c1df8633930071765b0957e",
    "version": 583335936,
    "bits": 386347065,
    "nonce": 2123739237,
    "size": 1279524,
    "weight": 3992829,
    "tx_count": 2105,
    "merkle_root": "656240e53d2e5d641716c3361b9c0e1893ec47844741e960a6e2eb5b1556e27e",
    "reward": 660918193,
    "total_fee_amt": 35918193,
    "avg_fee_amt": 17071,
    "median_fee_amt": 5320,
    "fee_amt_percentiles": [
      283,
      2982,
      3628,
      5320,
      9635,
      22560,
      1500000
    ],
    "avg_fee_rate": 35,
    "median_fee_rate": 23,
    "fee_rate_percentiles": [
      2,
      11,
      17,
      23,
      60,
      63,
      950
    ],
    "total_inputs": 4104,
    "total_input_amt": 1132134198635,
    "total_outputs": 14748,
    "total_output_amt": 1132098280442,
    "segwit_total_txs": 1664,
    "segwit_total_size": 1143955,
    "segwit_total_weight": 3450661,
    "avg_tx_size": 607.71,
    "utxoset_change": 10644,
    "utxoset_size": 83999968,
    "coinbase_raw": "033edf0b040d1df8632f466f756e6472792055534120506f6f6c202364726f70676f6c642f17e735588f06000000000000",
    "coinbase_address": "bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj",
    "coinbase_signature": "OP_0 OP_PUSHBYTES_20 35f6de260c9f3bdee47524c473a6016c0c055cb9",
    "coinbase_signature_ascii": "\u0003>ß\u000b\u0004\r\u001døc/Foundry USA Pool #dropgold/\u0017ç5X\u0006\u0000\u0000\u0000\u0000\u0000\u0000",
    "pool_slug": "foundryusa",
    "orphans": []
  }
```

**Comment by sha2fiddy** [comment]
@nymkappa this looks fantastic.  I'm pretty sure this fully covers everything we asked for, and the names are much clearer!

If I was going to nitpick anything (and I know it comes from Core this way), it's that the percentiles could labeled.  Something like `{'fee_min': n, 'fee_pctl_10': n, ...}`.  I'm very happy with the format as is, the explicit labeling is just something I'd want as a new user.

**Comment by nymkappa** [comment]
> @nymkappa this looks fantastic. I'm pretty sure this fully covers everything we asked for, and the names are much clearer!
> 
> If I was going to nitpick anything (and I know it comes from Core this way), it's that the percentiles could labeled. Something like `{'fee_min': n, 'fee_pctl_10': n, ...}`. I'm very happy with the format as is, the explicit labeling is just something I'd want as a new user.

How about this
```
[{
    ...
    "fee_amt_percentiles": {
      "min": 192,
      "perc_10": 1221,
      "perc_25": 1536,
      "perc_50": 2072,
      "perc_75": 3361,
      "perc_90": 8000,
      "max": 1481720
    },
    "avg_fee_rate": 16,
    "median_fee_rate": 11,
    "fee_rate_percentiles": {
      "min": 1,
      "perc_10": 6,
      "perc_25": 9,
      "perc_50": 11,
      "perc_75": 18,
      "perc_90": 20,
      "max": 801
    },
    ...
}]
```

**Comment by sha2fiddy** [comment]
> How about this

Perfect.

**Review by wiz — COMMENTED** [review]
Testing in progress @ 3108935

```
Feb 24 05:37:54 [14999] NOTICE: Disk cache contains an outdated schema version. Clearing it and skipping the cache loading.
```

```
Feb 24 05:37:54 [14999] ERR: Cannot get fetch orphaned blocks. Reason: Block not found on disk
```

```
% bitcoin-cli getchaintips
[
  {
    "height": 778066,
    "hash": "00000000000000000000744fd0873e109ece2c730b567de55611347e5407eaee",
    "branchlen": 0,
    "status": "active"
  },
  {
    "height": 777172,
    "hash": "0000000000000000000215ac1b6fd564d8d4707631f6b77273521eb1e242cf28",
    "branchlen": 1,
    "status": "headers-only"
  },
  {
    "height": 772981,
    "hash": "0000000000000000000682990a0dae862b48e0451d619938215dd47ed9560200",
    "branchlen": 1,
    "status": "headers-only"
  },
  {
    "height": 771627,
    "hash": "00000000000000000005a92bdb6f9d55ea8d2b42579e0db6ca7764f97b6910e1",
    "branchlen": 1,
    "status": "valid-headers"
  },
  {
    "height": 759781,
    "hash": "000000000000000000025edbf5ea025e4af2674b318ba82206f70681d97ca162",
    "branchlen": 1,
    "status": "valid-fork"
  }
]
```

**Comment by nymkappa** [comment]
> Feb 24 05:37:54 [14999] ERR: Cannot get fetch orphaned blocks. Reason: Block not found on disk

Fixed in https://github.com/mempool/mempool/pull/3070/commits/2be0146d7a77fb3345aa9e9170f1108a5ffef8c3

**Review by wiz — CHANGES_REQUESTED** [review]
I guess we'll need to limit this to enterprise customers only - it's too heavy to open to the public...

```
% curl -i https://node201.fmt.mempool.space/api/v1/blocks-bulk/1/760000
HTTP/2 504 
server: nginx
date: Fri, 24 Feb 2023 05:46:06 GMT
content-type: text/html
content-length: 160

<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by sha2fiddy** [comment]
> it's too heavy to open to the public...

I thought there might be issues with data volume.  Totally understandable if you need to add an upper limit to the num of blocks returned.


> I guess we'll need to limit this to enterprise customers only

Is there any possibility of including it in self-hosted installs / packaging into Umbrel etc?  Idea being it facilitates ppl or businesses to do analysis with sovereign from their node.

**Comment by wiz** [comment]
I think we can enable it with a max of 10 blocks per request, and then if you guys need we can add an API key or IP whitelist to get more than that

**Comment by sha2fiddy** [comment]
> I think we can enable it with a max of 10 blocks per request, and then if you guys need we can add an API key or IP whitelist to get more than that

Sounds good.  Lmk what you're thinking the increased limit might be for enterprise subscribers, so I can start planning our export scripts to handle full timechain 🤙

**Comment by nymkappa** [comment]
> Is there any possibility of including it in self-hosted installs / packaging into Umbrel etc? Idea being it facilitates ppl or businesses to do analysis with sovereign data from their node.

Yes. We've added a config setting (`config.MEMPOOL.MAX_BLOCKS_BULK_QUERY`) to set the maximum number of blocks that can be queried through the new API so self hosted instance can set this to whatever number they want, as soon as their hardware can handle it. We can probably set it to 100 on raspi distros, something like that.

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[210f939e](https://github.com/mempool/mempool/commit/210f939e)]

**Pull request merged**
