### PR TITLE
Added frontend section on docker readme

### PR DESCRIPTION
**Pull request by ja3090**
Expanded existing docs on how to override environment settings in the docker-compose file. Have also completed contributor instructions

Addresses #4191

### CODE REVIEW

**Comment by nymkappa** [comment]
Thanks! Can you squash your commits into one single commit please?

**Comment by jaw163** [comment]
Hey have just done that for you.

**Comment by nymkappa** [comment]
@jaw163 do you want to cleanup the formatting before we can merge it?

**Comment by knorrium** [comment]
Closing this stale PR. I'll review the overrides as we get ready to ship 3.0

**Pull request closed without merging**
