### PR TITLE
[search bar] fix alignment issue

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/3757

### CODE REVIEW

**Comment by hunicus** [comment]
Still seeing this...

Screenshot from 2023-05-14 17-03-08

For me removing [this line](https://github.com/mempool/mempool/pull/3773/files#diff-96529b531b1bc271ed6e8d3a79bda77aee8d8f06d7864fa8c6fa8fa517f09101R20) on top of these changes seems to fix the issue.

**Comment by nymkappa** [comment]
> Between 523px to 567px it's still present.

Between those resolution the search bar is wrapped into the next line. So I cannot reproduce.

Screenshot 2023-05-23 at 07 37 25

**Comment by nymkappa** [comment]
> > Between 523px to 567px it's still present.
> 
> Between those resolution the search bar is wrapped into the next line. So I cannot reproduce.
> Screenshot 2023-05-23 at 07 37 25

Found the small jump you guys mentioned, should be good now

**Review by softsimon — CHANGES_REQUESTED** [review]
Can still reproduce.. 550px width
Screenshot 2023-07-18 at 18 09 53

**Comment by nymkappa** [comment]
> Can still reproduce.. 550px width Screenshot 2023-07-18 at 18 09 53

Okay yeah it's broken on Chrome, works fine on Firefox. I'll check.

**Comment by nymkappa** [comment]
@softsimon Pushed another commit, looks good on Firefox, Chrome and Safari. Please check again

image

**Review by softsimon — APPROVED** [review]
tested ACK @ [9a2ab7fe]

**Pull request merged**
