### PR TITLE
Transparently redirect direct mobile tx visits to pizza tracker

### PR DESCRIPTION
**Pull request by mononaut**
_(requires https://github.com/mempool/mempool.space/pull/1205)_

This PR moves the new "Pizza Tracker" page under the same `/tx/:txid` route path as the main transaction page, and adds a `canMatch` route guard to selectively render the pizza tracker component if all of the following conditions are met:
 - Initial page load (i.e. not an internal navigation)
 - On mobile (`window.innerWidth <= 767.98`)
 - *NOT* overridden by query parameter `?mode=details`
 
If the mode=details query parameter is set in the URL, then the full transaction page will always be displayed, so this can be used to explicitly link to the main page instead of the pizza tracker.

When navigating to a /tx page internally on mobile, `?mode=details` is automatically added to prevent forcing the user back to the tracker view on page reload/refresh.

~~Leaving in draft for now because the tracker page needs some more polish before we funnel all of our `/tx/` traffic there.~~

### CODE REVIEW

**Comment by mononaut** [comment]
rebased on master, and taking out of draft (pending PR #5137)

**Comment by Zoiediez** [comment]
> rebased on master, and taking out of draft (pending PR #5137)

**Comment by mononaut** [comment]
rebased on current master & resolved merge conflicts

**Comment by mononaut** [comment]
this doesn't work with the hybrid build - I'll reopen once I figure out a fix

**Comment by mononaut** [comment]
hybrid build issues have been resolved, but the PR now needs to be tested & merged in tandem with https://github.com/mempool/mempool.space/pull/1205

**Review by wiz — APPROVED** [review]
utACK

**Pull request merged**
