### PR TITLE
smoothed graphs

### PR DESCRIPTION
**Pull request by pfoytik**
This pull request takes a stab at #2269 it creates a moving average line over top of the Mempool by vBytes chart to show a smoothed curve in addition to the data plots.

image

The moving average line is set to be white as it stands out best among the default colors of the chart and dark theme. The moving average window size is set to 10 as a default, but is a variable MAWindowsSize at the top of mempool-graph.components.ts. The MA is currently displayed over all time frames, but this could be adjusted to only show for the larger time frames if needed. We could also add the ability for users to change the windowsize for the moving average (smaller windows size will reflect more recent movement and larger windowsize will smooth out the MA more).

### CODE REVIEW

**Review by softsimon — CHANGES_REQUESTED** [review]
It seems the changes to `docker/README.md` is not related to this PR.
And could you remove the `package-lock.json` commit?

**Comment by pfoytik** [comment]
Sorry about that, I think it should be good now!

**Comment by softsimon** [comment]
> Sorry about that, I think it should be good now!

There's still a package lock and 2 gitignore files modified

**Comment by pfoytik** [comment]
> > Sorry about that, I think it should be good now!
> 
> There's still a package lock and 2 gitignore files modified

This git repo got messy, this was my fault. I'm going to resubmit a clean pull, sorry about that.

**Comment by nymkappa** [comment]
Thanks for giving this a shot but you applied the moving average on the wrong chart. The issue you are referencing mentions the incoming tx chart.

**Comment by pfoytik** [comment]
> Thanks for giving this a shot but you applied the moving average on the wrong chart. The issue you are referencing mentions the incoming tx chart.

Thanks for the reply, I have moved this pull request to : #3921
This is the same chart that is linked in the issue isn't it? I used the same link to the graph provided in the description of the issue: 
image

**Comment by nymkappa** [comment]
> > Thanks for giving this a shot but you applied the moving average on the wrong chart. The issue you are referencing mentions the incoming tx chart.
> 
> 
> 
> Thanks for the reply, I have moved this pull request to : #3921
> 
> This is the same chart that is linked in the issue isn't it? I used the same link to the graph provided in the description of the issue: 
> 
> image
> 
> 

Scroll down

**Comment by pfoytik** [comment]
> > > Thanks for giving this a shot but you applied the moving average on the wrong chart. The issue you are referencing mentions the incoming tx chart.
> > 
> > 
> > Thanks for the reply, I have moved this pull request to : #3921
> > This is the same chart that is linked in the issue isn't it? I used the same link to the graph provided in the description of the issue:
> > image
> 
> Scroll down

Gotcha! I'll check it out. Thanks again for the clarification :)

**Pull request closed without merging**
