### PR TITLE
Add translation for Thai language.

### PR DESCRIPTION
**Pull request by Gusb3ll**

### CODE REVIEW

**Comment by softsimon** [comment]
If you want to help translate to Thai language.. You need to sign up on Transifex and apply as a Thai translator https://www.transifex.com/mempool/mempool/

**Comment by Gusb3ll** [comment]
Oh ok, sorry for not asking first.

**Comment by softsimon** [comment]
> Ok, sorry for not asking first.

I'm sorry you had to spend the time translating a file. Unfortunately we can't use the file because Transifex is generating the file for us.

I accepted your request on Transifex now.. Using this tool it's easier to translate. You simply type the translation, use the Google translate-button for a quick result ,, and press Tab to go to the next word.

**Comment by Gusb3ll** [comment]
Alright, I'll hop on to it now tysm

**Pull request closed without merging**
