### PR TITLE
Accelerator dashboard

### PR DESCRIPTION
**Pull request by mononaut**
This PR adds a basic dashboard of public accelerator data at `/acceleration`:

acceleration-dash

The chart of acceleration fees and the list of recent accelerations also have full-page versions at `/graphs/acceleration/fees` and `/acceleration-list`.

### CODE REVIEW

**Comment by mononaut** [comment]
Rebased on master

**Comment by wiz** [comment]
@mononaut when you get a chance can you please rebase onto current master

**Comment by mononaut** [comment]
rebased on current master

**Comment by Fireskull81** [comment]
> rebased on current master

**Comment by nymkappa** [comment]
image

I'd use one of the side to show the currently accelerating stats instead.

We can still show both timespan using a simple switch like this one:
image

**Comment by nymkappa** [comment]
There is a small css issue here
image

**Comment by nymkappa** [comment]
It'd be interesting to show the fiat values as well, like in other dashboards
image

image

**Comment by nymkappa** [comment]
ALso, in the services backend, we consider an acceleration to be successful or failed only after 3 confirmations. So the following dashboard data is not valid. It shows 1 transaction as "accelerated" even tho the block was mined by a non participating mining pool. We are going to mark the acceleration as failed after 3 confirmations. This is to reduce the potential issue related to re-orgs.

Screenshot 2023-12-01 at 4 34 44 PM
Screenshot 2023-12-01 at 4 34 36 PM

**Review by nymkappa — CHANGES_REQUESTED** [review]
### `/acceleration-list` is quite broken

I don't think this page is relevant for now since you can get similar info from the block audit. If you want to polish it feel free to do so, otherwise just disable the page for now (and remove the link to it from the dashboard)

image

### Color issue

I think the "faded" effect looks weird here. IMO, we can just display them all in normal colors, similar to the RBF replacement widget where status does not matter.
Even a "canceled" acceleration request had a role to play in the fee market so it's fine to show it in normal color.
Screenshot 2023-12-04 at 2 33 34 PM

### Need to find more relevant data point to show here

This represents the maximum fee delta that can be collected by mining pools. However it will rarely be the case as block median fee rate will most of the time be much lower that the maximum "fee rate set by the user".
image


Here maybe we can show the sum of actual fee paid by users upon successful acceleration
image

### Mobile

The widgets on mobile looks odd vs other dashboard

Screenshot 2023-12-04 at 2 48 04 PM

This is visually more appealing because it's a bit more centered
Screenshot 2023-12-04 at 2 47 54 PM

Recent acceleration widget does not show txid link at all on mobile
image

**Comment by mononaut** [comment]
Updated with a new design:

Screenshot 2023-12-08 at 1 07 14 PM

**Review by wiz — APPROVED** [review]
Tested ACK @ v3.0.0-dev [aff44d90][44f883bc]

**Review by mihaiepure1977 — COMMENTED** [review]
Je vous demande de ma ramburser mon argant

**Comment by nymkappa** [comment]
> Je vous demande de ma ramburser mon argant

Nous ne faisons qu'afficher des données sur le réseau Bitcoin. On ne peux pas vous aider.

**Pull request merged**
