### PR TITLE
[accelerator] refresh checkout state logout

### PR DESCRIPTION
**Pull request by nymkappa**
Builds on top of https://github.com/mempool/mempool/pull/5242

When user logs out, we restart the accelerator checkout process from scratch.

Here is a sample of the current behavior (using #5242):

https://github.com/mempool/mempool/assets/9780671/5e129e54-ccad-4530-915e-3932ddb9dacd

New behavior (using this PR):

https://github.com/mempool/mempool/assets/9780671/c96d2977-240a-4c7c-975d-17fe2dd4c32c

### CODE REVIEW

**Comment by mononaut** [comment]
concept ACK

After logging out and then clicking the "accelerate" button again, I get redirected to the login page. Is that fixed separately in #5242?

**Comment by mononaut** [comment]
> To test alongside https://github.com/mempool/mempool.space/pull/1091

ah, I missed this part

**Review by mononaut — APPROVED** [review]
Tested ACK @ [75c9e15e][14e60402]

**Review by softsimon — APPROVED** [review]
Tested ACK @ v3.0.0-dev [75c9e15e1][14e60402]

**Pull request merged**
