### PR TITLE
Extend flow diagram to differentiate spent and unspent TXOs

### PR DESCRIPTION
**Pull request by mononaut**
This PR adds some visual differentiation between spent and unspent TXOs in the flow diagram.

The general idea is to suggest that the diagram for this specific transaction is part of a larger UTXO graph, so spent outputs 'connect' to the input line for some other transaction, while unspent outputs remain unconnected.

Continuing the concept, regular inputs have a matching connector, while coinbase inputs and liquid peg-ins do not.

This change is limited to the transaction page, and not reflected in unfurler previews.

Examples:

| | |
|-|-|
| Regular tx with one unspent and one spent output | spent-unspent-2 |
| Larger tx, showing appearance with small input/output lines | larger-tx |
| Testnet coinbase (with spent output) | testnet-spent-coinbase |
| Liquid peg-in (with spent output) | liquid-pegin |

### CODE REVIEW

**Review by softsimon — CHANGES_REQUESTED** [review]
Could you add the `cursor: pointer` to the new connectors to indicate clickability?

Another thought I had was, now with the connectors, maybe the regular flow-lines links should just jump to reveal the UTXO below, and only the connector will take you to the transaction? (Just an idea if it makes sense)

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ 6b9ac8a26c9d3615bf5d94b63816a33b365dd2bc

When clicking on a spent TXO on liquid that has confidential transactions, a `Error: Invalid blinding data (invalid number)` error is displayed, i.e. `/tx/d27370573b4bb0ea40f26027373f641b740d66dc029526069ce2143af9d1acbf?showFlow=true#flow=&vin=0`

Screen Shot 2022-10-31 at 11 32 21

**Comment by mononaut** [comment]
Good catch, I've just pushed a fix.

The liquid unblinding code assumed any url fragment must be a blinding factor, so it was throwing errors trying to parse `#vout=...` etc.

I've rewritten that part using URLSearchParams, so it'll play nice with the new vin/vout syntax and other anchor tags.

Here's a Liquid txid with blinding factors to verify unblinding still works: `/tx/1a7f371207ca5a1d13d8ab3dab7fb7a9e05288fe922665e30731adddddd81ecb#blinded=800,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,90fb24aab49dfd862e60161ae621f9dc9679f3197b55e6b1b7454155c94a1b7f,4f07afe0d712e80b91319eaadcb3401ee22e6f88caa1f0faadfd9ea7bc95abfe,900,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,6ca03a3942ea11ccec276fe5750e2859fe53b33d0a840f71818161620682cca0,a00df580064426065097de14b92023b0da2e900f8607e42fade2da46235edf6b`

**Comment by mononaut** [comment]
I've also added cursor:pointer and mouse event handling to the line endcaps and connectors.

**Comment by mononaut** [comment]
> Another thought I had was, now with the connectors, maybe the regular flow-lines links should just jump to reveal the UTXO below, and only the connector will take you to the transaction? (Just an idea if it makes sense)

I gave this a try, but the shape & size of the connector element makes it quite difficult to click, especially for smaller utxos.

**Review by softsimon — CHANGES_REQUESTED** [review]
To improve intuitivity

* Clicking on the main bands should just highlight and take you down to the UTXOs both on input and outputs
* The "connector" should be a separate highlighted button that takes you to the previous or next UTXO
* Perhaps something different in the tooltip to clarify the difference

**Comment by mononaut** [comment]
Updated:
 - clicking on inner band scrolls to the input/output in the list
 - clicking on the outer connector navigates to the connected transaction
 - tooltip for the outer connector shows the txid and vin/vout number of the connected transaction
 
Screenshot 2022-11-22 at 10 14 39 AM

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[4abd77fe](https://github.com/mempool/mempool/commit/4abd77fe)]

**Review by softsimon — APPROVED** [review]
tested ACK

**Pull request merged**
