### PR TITLE
Fix mining dashboard meta description not showing

### PR DESCRIPTION
**Pull request by hunicus**
Also add some descriptions missing from #4221.

To test these changes, verify that meta description elements render correctly for the following URLs:
- `/mining`
- `/blocks`
- `/graphs/mining/pools-dominance`
- `/graphs/lightning/nodes-per-isp`

And on Liquid, any asset page, e.g.:
- `/assets/asset/ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2`

### CODE REVIEW

**Comment by softsimon** [comment]
@hunicus could you rebase on master

**Comment by hunicus** [comment]
@softsimon done.

**Comment by hunicus** [comment]
@softsimon done.

**Review by softsimon — APPROVED** [review]
utACK

**Pull request merged**
