### PR TITLE
Allow syncing external backend assets using Tor

### LINKED ISSUE #1426: Asset download should happen over socks5 if config uses that
### Description

mempool-config includes an option to set up a tor proxy. This is currently used to download price data. However when the external pools asset file is downloaded, the proxy setting is not used

#### Version

0bada4b07932a996dd4c9b0d3860b86109c612ec

### Expected behaviour

If config includes socks5 then it should be used for all requests

### Actual behaviour

socks5 is only used for price data

### PR DESCRIPTION
**Pull request by knorrium**
Fix #1426

Clearnet:
```
Mar 23 08:08:35 [12093] INFO: Downloading external asset pools.json over clearnet...
Mar 23 08:08:35 [12093] INFO: External asset pools.json saved to ./pools.json
```

Tor:

``` 
Mar 23 08:06:35 [11621] INFO: Downloading external asset pools.json over the Tor network...
  agent-base Resolving socket for 'https:' request: 'GET /mempool/mining-pools/master/pools.json' +0ms
  socks-proxy-agent Creating socks proxy connection: { proxy: { host: '127.0.0.1', port: 50090, type: 5 }, destination: { host: 'raw.githubusercontent.com', port: 443 }, command: 'connect', timeout: undefined } +0ms
  socks-proxy-agent Successfully created socks proxy connection +340ms
  socks-proxy-agent Upgrading socket connection to TLS +1ms
Mar 23 08:06:36 [11621] INFO: External asset pools.json saved to ./pools.json
```

invalid config:

``` 
Mar 23 08:07:21 [11776] INFO: Downloading external asset pools.json over the Tor network...
  agent-base Resolving socket for 'https:' request: 'GET /mempool/mining-pools/master/pools.json' +0ms
  socks-proxy-agent Creating socks proxy connection: { proxy: { host: '127.0.0.1', port: 50091, type: 5 }, destination: { host: 'raw.githubusercontent.com', port: 443 }, command: 'connect', timeout: undefined } +0ms
backend/dist/sync-assets.js:55
            throw new Error(`Failed to download external asset. ` + e);
                  ^

Error: Failed to download external asset. Error: connect ECONNREFUSED 127.0.0.1:50091
```

### CODE REVIEW

**Comment by visskiss** [comment]
I would be more tempted to abstract fetching assets into its own class given you have replicated the code for fetching in two separate files.

**Comment by knorrium** [comment]
> I would be more tempted to abstract fetching assets into its own class given you have replicated the code for fetching in two separate files.

PRs are welcome

**Comment by visskiss** [comment]
Would like to assist, but I'm not a node developer.

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.4.0-dev [[89d62b7b](https://github.com/mempool/mempool/commit/89d62b7b)]

Worked well downloading pools.json over clearnet, didn't test Tor but I'll let the requester of this feature test that on their own :)

**Pull request merged**
