### PR TITLE
hybrid acceleration checkout

### PR DESCRIPTION
**Pull request by mononaut**
_(includes & supersedes PRs #5218 and #5220)_

This draft PR implements a huge refactor to merge and redesign the acceleration preview & checkout components.

The new combined component supports checkout flows for logged-in users with balances and "simple mode" via lightning or cashapp, via either the tx or pizza tracker pages.

### "summary"
default initial screen for logged-in users, and for the /tracker page

`/tx`:
the "customize" button switches to the "advanced" screen.
the "accelerate" button submits the acceleration request, paying from user balance.
Screenshot 2024-06-28 at 7 12 51 AM

`/tracker`:
the "accelerate" button progresses to the "checkout" screen.
Screenshot 2024-06-28 at 7 13 23 AM

---

### "checkout"
default initial screen for not-logged-in users on the /tx page
`/tx`:
Screenshot 2024-06-28 at 7 18 57 AM 

`/tracker`:

---

### "cashapp"
cashapp payment confirmation screen

Screenshot 2024-06-28 at 7 19 11 AM

---

### "advanced"
only for logged-in users on the /tx page.
"details" button toggles between condensed and full views.
"Accelerate" button progresses to the "summary" screen.

Screenshot 2024-06-28 at 7 14 11 AM

---

## UI Flows

```mermaid
graph TD
    subgraph "/tx (logged in)"
        X(["click accelerate"])
        A["summary"]
        D["advanced"]
        Y(["accelerated"])
    end

    X -.-> A
    A -->|customize| D
    D -->|accelerate| A
    A -->|accelerate| Y
    
```

```mermaid
graph TD
    subgraph "/tx (no user)"
        X(["click accelerate"])
        B["checkout"]
        C["cashapp"]
        Y(["accelerated"])
    end

    X -.-> B
    B -->|pay lightning| Y
    B -->|cashapp| C
    C -->|pay cashapp| Y
    C -->|go back| B
```

```mermaid
graph TD
    subgraph "/tracker (logged in)"
        X(["load page"])
        A["summary"]
        B["checkout"]
        Y(["accelerated"])
    end

    X -.-> A
    A -->|accelerate| B
    B -->|pay lightning| Y
    B -->|go back| A
```

```mermaid
graph TD
    subgraph "/tracker (no user)"
        X(["load page"])
        A["summary"]
        B["checkout"]
        C["cashapp"]
        Y(["accelerated"])
    end

    X -.-> A
    A -->|accelerate| B
    B -->|pay lightning| Y
    B -->|cashapp| C
    C -->|pay cashapp| Y
    C -->|go back| B
```

---

TODO:
- [x] confirm backend support
- [x] consolidate & fix success/error messages
- [x] test full payment flow

### CODE REVIEW

**Review by softsimon — APPROVED** [review]
tested ACK @ [35d0e7fae]

**Comment by softsimon** [comment]
* Remove the auto-scroll when LN payment show up, or scroll up when the acceleration-arrow shows up
* The accelerate-sound isn't playing when accelerating with LN. Should be played on arrow swoooosh.

**Comment by mononaut** [comment]
> * Remove the auto-scroll when LN payment show up, or scroll up when the acceleration-arrow shows up
> * The accelerate-sound isn't playing when accelerating with LN. Should be played on arrow swoooosh.

should be fixed.

the acceleration sound is now played when the invoice is detected as paid, which might be a little before the arrow swoosh, but in line with the behavior for account-based & cashapp accelerations.

**Review by wiz — APPROVED** [review]
LFG

**Pull request merged**
