### PR TITLE
Merge audit feature into main block page

### LINKED ISSUE #2717: Merge Block Audit into Block page
* Remove the separate block audit page and move it into and replace the current Block page top view.
* Move the Fee-ralated data (Median fee, total fee, subsidy, Miner detection) to the top
* Move the Audit data ( Removed txs, added txs etc) to below similar to Transaction Details, or under a Audit stats block that's toggleble under a button.

### PR DESCRIPTION
**Pull request by mononaut**
This PR resolves #2717 by displaying the side-by-side block audit view on the main block page.

merge-block-audit

The PR also extends the BlockAuditRepository with a list of 'fresh' transactions which arrived within 3 minutes of the block, so that we can label those in the tooltip:

fresh-tooltip

### CODE REVIEW

**Review by softsimon — CHANGES_REQUESTED** [review]
Optimize SQL query to fetch batched block audit scores

**Comment by mononaut** [comment]
done

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[de049148](https://github.com/mempool/mempool/commit/de049148)]

**Review by danger89 — APPROVED** [review]

**Comment by danger89** [comment]
Thank you!

**Pull request merged**
