### PR TITLE
Simplify packaging for backend

### PR DESCRIPTION
**Pull request by erikarvstedt**
This PR fixes all issues in #2092 for the bitcoin backend.

### TODO
I haven't tested PWD-invariance for the Bisq and Liquid backends.
`api/liquid/icons.ts` still uses a [PWD-relative path](https://github.com/mempool/mempool/blob/2f0c8d94b0bf07da1a081c5982625a562d9d3425/backend/src/api/liquid/icons.ts#L5) to `icons.json`, but this files seems to be dynamically generated (where?). I don't know what's the best way to fix this (or whether a fix is needed).

### Discussion

All changes in this PR are backwards-compatible; the Docker image still uses the old working directory.

### CODE REVIEW

**Review by Capi5879 — APPROVED** [review]

**Comment by wiz** [comment]
@knorrium could you please review/test this when you have a chance to make sure the Docker builds are ok?

**Comment by knorrium** [comment]
@erikarvstedt apologies for the extremely long delay to get back to you on this. We had issues with the Docker build on GitHub and we were focused on the Lightning features. Would you mind solving the merge conflicts so we can try your changes with the fixes to the Github builder?

**Comment by knorrium** [comment]
@erikarvstedt apologies for the extremely long delay to get back to you on this. We had issues with the Docker build on GitHub and we were focused on the Lightning features. Would you mind solving the merge conflicts so we can try your changes with the fixes to the Github builder?

**Comment by erikarvstedt** [comment]
Rebased to master.

**Comment by erikarvstedt** [comment]
Rebased to master.

**Comment by knorrium** [comment]
Thanks - just kicked off a build and will check it out later.

**Comment by knorrium** [comment]
Running the built v2.5.0-dev [[34c8ad61](https://github.com/mempool/mempool/commit/34c8ad61)] Docker image on my local Umbrel instance - upgrade path went fine. Doing a clean install next.

**Comment by knorrium** [comment]
Ran the initial indexing with the new image and everything looks fine.

Found an issue along the way which should now be fixed in #2506 

 ```
$ docker logs mempool_api_1 --follow
wait-for-it.sh: waiting 720 seconds for mariadb:3306
wait-for-it.sh: mariadb:3306 is available after 12 seconds
sed: -e expression #1, char 103: unterminated `s' command
sed: -e expression #1, char 102: unterminated `s' command
Sep  3 04:45:21 [122] NOTICE: Starting Mempool Server... (34c8ad6)
Sep  3 04:45:22 [122] INFO: Database connection established.
Sep  3 04:45:22 [122] INFO: Initializing database (first run, clean install)
Sep  3 04:45:22 [122] INFO: Connected to Electrum Server at 10.21.21.10:50001 (["electrs/0.9.4","1.4"])
Sep  3 04:45:28 [122] NOTICE: MIGRATIONS: Initializing database schema version number to 40
Sep  3 04:45:28 [122] NOTICE: MIGRATIONS: OK. Database schema has been properly initialized to version 40 (latest version)
Sep  3 04:45:28 [122] INFO: Starting statistics service
Sep  3 04:45:28 [122] INFO: Starting currency rates service
Sep  3 04:45:28 [122] INFO: Currency rates service will be queried over clearnet using https://price.bisq.wiz.biz/getAllMarketPrices
Sep  3 04:45:28 [122] NOTICE: Mempool Server is running on port 8999
Sep  3 04:45:28 [122] INFO: Updating latest mining pools from https://raw.githubusercontent.com/mempool/mining-pools/master/pools.json over clearnet
Sep  3 04:45:29 [122] INFO: Downloading pools.json for the first time from https://raw.githubusercontent.com/mempool/mining-pools/master/pools.json
Sep  3 04:45:29 [122] WARN: No slug found for 'OKMINER', generating it => 'okminer'
Sep  3 04:45:29 [122] WARN: No slug found for 'ULTIMUS POOL', generating it => 'ultimuspool'
Sep  3 04:45:29 [122] INFO: Mining pools.json import completed
Sep  3 04:45:29 [122] NOTICE: PoolsUpdater completed
Sep  3 04:45:35 [122] INFO: Cannot save block price for 752351 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:38 [122] INFO: Cannot save block price for 752352 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:41 [122] INFO: Cannot save block price for 752353 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:45 [122] INFO: Cannot save block price for 752354 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:48 [122] INFO: Cannot save block price for 752355 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:52 [122] INFO: Cannot save block price for 752356 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:55 [122] INFO: Cannot save block price for 752357 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:45:58 [122] INFO: Cannot save block price for 752358 because the price updater hasnt completed yet. Trying again in 10 seconds.
Sep  3 04:47:29 [122] NOTICE: The mempool is now in sync!
Sep  3 04:47:31 [122] NOTICE: Inserted 168 MtGox USD weekly price history into db
Sep  3 04:47:35 [122] NOTICE: Inserted 466 Kraken EUR, USD, GBP, JPY, CAD, CHF and AUD weekly price history into db
Sep  3 04:47:35 [122] INFO: Fetching daily price history from exchanges and saving missing ones into the database, this may take a while
Sep  3 04:47:55 [122] NOTICE: Inserted 2004 daily historical prices into the db
Sep  3 04:47:55 [122] INFO: Fetching hourly price history from exchanges and saving missing ones into the database, this may take a while
Sep  3 04:48:06 [122] NOTICE: Inserted 714 hourly historical prices into the db
Sep  3 04:48:06 [122] INFO: Indexing 9985 blocks from #752358 to #742359
Sep  3 05:45:10 [122] INFO: Indexing 10000 blocks from #742358 to #732359
Sep  3 06:42:37 [122] INFO: Indexing 10000 blocks from #732358 to #722359
Sep  3 07:40:40 [122] INFO: Indexing 10000 blocks from #722358 to #712359
Sep  3 08:36:48 [122] INFO: Indexing 10000 blocks from #712358 to #702359
Sep  3 09:36:18 [122] INFO: Indexing 2560 blocks from #702358 to #699799
Sep  3 09:49:55 [122] NOTICE: Block indexing completed: indexed 52545 blocks
Sep  3 09:49:56 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 09:49:58 [122] NOTICE: Indexed 28 difficulty adjustments
Sep  3 09:50:01 [122] NOTICE: Daily network hashrate indexing completed: indexed 359 days
Sep  3 09:50:06 [122] NOTICE: Weekly mining pools hashrates indexing completed: indexed 7140
Sep  3 10:50:13 [122] INFO: Latest BTC fiat averaged price: {"USD":19826,"EUR":19925,"GBP":17218,"CAD":26024,"CHF":19431,"AUD":29167,"JPY":2782261}
Sep  3 10:50:14 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 11:50:21 [122] INFO: Latest BTC fiat averaged price: {"USD":19792,"EUR":19893,"GBP":17191,"CAD":25996,"CHF":19420,"AUD":29157,"JPY":2778038}
Sep  3 11:50:23 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 12:50:32 [122] INFO: Latest BTC fiat averaged price: {"USD":19834,"EUR":19924,"GBP":17219,"CAD":26027,"CHF":19458,"AUD":29164,"JPY":2781928}
Sep  3 12:50:34 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 13:50:41 [122] INFO: Latest BTC fiat averaged price: {"USD":19885,"EUR":19978,"GBP":17258,"CAD":26105,"CHF":19474,"AUD":29194,"JPY":2790905}
Sep  3 13:50:43 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 14:50:51 [122] INFO: Latest BTC fiat averaged price: {"USD":19820,"EUR":19909,"GBP":17216,"CAD":25988,"CHF":19453,"AUD":29172,"JPY":2781665}
Sep  3 14:50:52 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation
Sep  3 15:51:00 [122] INFO: Latest BTC fiat averaged price: {"USD":19769,"EUR":19867,"GBP":17171,"CAD":25940,"CHF":19400,"AUD":29184,"JPY":2773934}
Sep  3 15:51:02 [122] INFO: Some blocks are not indexed, skipping missing blocks during chain validation

```

**Review by knorrium — APPROVED** [review]
Tested ACK on Umbrel @ v2.5.0-dev [[34c8ad61](https://github.com/mempool/mempool/commit/34c8ad61)]

@wiz Please merge this one before any other merge conflicts happen.

**Comment by wiz** [comment]
@knorrium please rebase onto current master to fix merge conflict

**Pull request merged**
