### PR TITLE
Liquid support for unblinding transactions.

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
## Reference links

Issue Mempool.Space
https://github.com/mempool/mempool/pull/523

Issue Marina Wallet
https://github.com/vulpemventures/marina/issues/105

Blockstream link example with #blinded hash url.
https://blockstream.info/liquid/tx/16e987d626adfa4dbf50312a9b8e31571531f9b8e5407c49d8e0b3dc4ac707ac#blinded=160252405,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,a50c70e9049a6a49f895b6bbadf7d4c212b1940b9748603fc006d3de1092bcbd,8b0ec267d4260102439c29abeb6fa606997cc4ee86fcd996bd82a462a78ee3c8,26252,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,57bfaf037eea2f910e73c39e543306317ecda6d9e8c30a3273f92b3447cb22f4,bc230d8ee0d9503d4cd6081facd71f0e37a45fc2c475eae154da90ebee1ae087

## Dependency

Elements Project Libwally Core
https://github.com/ElementsProject/libwally-core

## Copied files from Blockstream/esplora

Functions that blind and unblind txs
https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/driver/blinding.js
https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/lib/libwally.js

Docker 
https://github.com/Blockstream/esplora/blob/4b03819f295fdc51e7fb00dc2e852da641f170cd/Dockerfile.deps

## Run Docker to export wallycore.js
``` bash
cd docker/frontend/wally-core

docker build -t wally-core .

docker run -dit wally-core

docker ps -a

docker cp <container_id>:/srv/wally_wasm/ ./

docker stop <container_id>
```   
## Test on your local environment:
http://localhost:4200/liquid/tx/16e987d626adfa4dbf50312a9b8e31571531f9b8e5407c49d8e0b3dc4ac707ac#blinded=160252405,ce091c998b83c78bb71a632313ba3760f1763d9cfcffae02258ffa9865a37bd2,a50c70e9049a6a49f895b6bbadf7d4c212b1940b9748603fc006d3de1092bcbd,8b0ec267d4260102439c29abeb6fa606997cc4ee86fcd996bd82a462a78ee3c8,26252,6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d,57bfaf037eea2f910e73c39e543306317ecda6d9e8c30a3273f92b3447cb22f4,bc230d8ee0d9503d4cd6081facd71f0e37a45fc2c475eae154da90ebee1ae087

### CODE REVIEW

**Comment by wiz** [comment]
Instead of adding the Dockerfile, how about simply fetching the latest release from their GitHub page? https://github.com/ElementsProject/libwally-core/releases

**Comment by MiguelMedeiros** [comment]
> Instead of adding the Dockerfile, how about simply fetching the latest release from their GitHub page? https://github.com/ElementsProject/libwally-core/releases

I tried to download [wallycore-wasm](https://github.com/ElementsProject/libwally-core/releases/download/release_0.8.3/wallycore-wasm.tar.gz), but when I run the code it shows an error saying there is no `InitWally` function.

The Docker I got from Blockstream/Esplora adds a module named `InitWallet`.

https://github.com/mempool/mempool/blob/bb7c04c51550f70d4067fe04dc2bd43b0276e1c6/docker/frontend/wally-core/Dockerfile#L7

image

That's why I made a tutorial to export this webassembly and saved the docker in case we need to re-compile again.
But that we can take away, if we need to update the `wallycore-wasm` we compile and overwrite the files in the repository.

Can I leave a tutorial on the Wiki explaining how to export `wallycore-wasm`? So we don't get lost in the future?

**Review by knorrium — CHANGES_REQUESTED** [review]
> The Docker I got from Blockstream/Esplora adds a module named `InitWallet`.

This is a compiler flag. You could refactor the code so it's not needed and you could just use the latest release as @wiz pointed out. It's also important to keep track of what version is being used.

See https://emscripten.org/docs/getting_started/FAQ.html

**Comment by MiguelMedeiros** [comment]
Tasks:
- [x] Delete the `dockerfile` ([fix](https://github.com/mempool/mempool/pull/588#issuecomment-864117478))
- [x] Delete the `wallycore.html` ([fix](https://github.com/mempool/mempool/pull/588#discussion_r654763992))
- [x] Validate unblided tx varibles ([fix](https://github.com/mempool/mempool/pull/588#discussion_r654763888))
- [x] Add deduced blinded for inputs (`vin.prevout`) - [deduce-blinded.js](https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/lib/deduce-blinded.js)
- [x] Add error messages.
- [x] Add cypress e2e testing for unblinded tx.
- [ ] Add an endpoint for unblinded tx.
- [ ] Load `libwally,js` dynamically.

## Dependencies
Elements Project Libwally Core
https://github.com/ElementsProject/libwally-core
Webassembly Component - v0.8.3
https://github.com/ElementsProject/libwally-core/releases/download/release_0.8.3/wallycore-wasm.tar.gz

#### Copied/refactored files from Blockstream/esplora
Functions that blind/unblind txs (vins and vouts):
https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/driver/blinding.js
https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/lib/libwally.js
https://github.com/Blockstream/esplora/blob/4cc726d586e6187a019ef979b288566ead98d0a4/client/src/lib/deduce-blinded.js

**Review by softsimon — APPROVED** [review]

**Pull request merged**
