### PR TITLE
Unfurler fallback images & bisq support

### PR DESCRIPTION
**Pull request by mononaut**
This PR refactors the unfurler to improve route handling. The unfurler now:
 - Handles Bisq urls
 - Supports setting static preview images at specific urls
 - Returns fallback images instead of a 500 error when rendering fails
 
The same static/fallback images are used across mainnet/signet/testnet variants for now.
 
I've provisionally configured the following:

(The "static" dashboard image is only used on that exact route, while the fallback images are used for all subroutes without dynamic unfurls, and when rendering fails.)

| Type | Routes | Image |
|-|-|-|
| Static | main mempool dashboard only | dashboard |
| Fallback | all `.../mining/**` routes | mining |
| Fallback | all `.../lightning/**` routes | lightning |
| Fallback | everything else on mempool.space (e.g. `/address/invalid` or `/about`) | mempool-space-preview (the existing default) |
| Fallback | everything on liquid.network (e.g. `/tx/invalid` or `/assets`) | liquid-network-preview (the existing default) |
| Fallback | everything on bisq.markets | bisq-markets-preview (the existing default) |

The new static/fallback images are hosted on the main frontend under `/resources/previews/...`. In the case of dynamic rendering fallbacks, the images are proxied on-the-fly from the configured frontend by the unfurler.

### CODE REVIEW

**Comment by pedromvpg** [comment]
What do you think of something more mysterious and less information heavy? Just teasing a part of the chart.

image

**Comment by mononaut** [comment]
> What do you think of something more mysterious and less information heavy? Just teasing a part of the chart.

I love this, looks much cleaner at small display sizes, and it seems sensible to avoid showing specific numbers since these static images will get out of date quickly.

Maybe we could do something similar with the mempool fee composition graph for the main dashboard image, and the map for lightning?

**Comment by pedromvpg** [comment]
How's this?

**Comment by pedromvpg** [comment]
How's this?

image

**Comment by wiz** [comment]
@pedromvpg thanks for making the nice images, but we're changing the slogan for v2.5 to "Explore the full Bitcoin ecosystem with mempool.space"

**Comment by wiz** [comment]
@pedromvpg thanks for making the nice images. We're changing the slogan for v2.5 to "Explore the full Bitcoin ecosystem with mempool.space", but I think we should just use "mempool" instead of the slogan to go along with the "mining" and "lightning" dashboard titles

**Review by wiz — APPROVED** [review]
Tested ACK @ 0f5e4d3a15a235ffdc940c2f93f3c5bf4ea537d4

**Comment by pedromvpg** [comment]
Any of these 2 options work?

image

**Comment by pedromvpg** [comment]
image

[mempool open graph images.zip](https://github.com/mempool/mempool/files/9453703/mempool.open.graph.images.zip)

**Pull request merged**
