### PR TITLE
Mining dashboard still runs fine if Bitcoin Core becomes unavailable

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/1705

Depends on https://github.com/mempool/mempool/pull/1696 which must be merged first to avoid conflicts, as this branch is forked from `nymkappa/feature/merge-blocks`

#### Testing

* Run bitcoind
* Run mempool backend + frontend
* Wait a couple of seconds for things to start
* Stop bitcoind
* Open the browser network tab and disable the cache
* Browse mining dashboard pages with ease(tm). You will notice some value being zeroed.

### CODE REVIEW

**Comment by wiz** [comment]
please rebase onto current master

**Comment by nymkappa** [comment]
> please rebase onto current master

Rebased and force pushed

**Comment by wiz** [comment]
```
May 31 08:06:38 [54148] DEBUG: Bitcoin Core is not available, using zeroed value for current hashrate
```
Might want to make this a WARN instead of DEBUG, but it seems to make a shitload of messages, so maybe limit them somehow

**Review by wiz — APPROVED** [review]
Tested ACK v2.4.0-dev [[687310f6](https://github.com/mempool/mempool/commit/687310f6)]

Seems OK, but needs more testing.

**Pull request merged**
