### PR TITLE
Polish CPFP button

### PR DESCRIPTION
**Pull request by softsimon**
* CPFP consistently smaller
* Consistently removed the info-icon
* Updated the header title of the cpfp pane

Screenshot 2024-10-11 at 17 13 12

### CODE REVIEW

**Comment by wiz** [comment]
@orangesurf @mononaut can you bikeshed on what the correct terminology should be for the CPFP section? "transaction family tree" or something?

**Comment by orangesurf** [comment]
> @orangesurf @mononaut can you bikeshed on what the correct terminology should be for the CPFP section? "transaction family tree" or something?

Related Transactions?

**Comment by softsimon** [comment]
Title now says Related Transactions 

Screenshot 2024-10-25 at 11 58 23

**Comment by softsimon** [comment]
self test ACK

**Pull request merged**
