### PR TITLE
hide infinite spinner on 404

### PR DESCRIPTION
**Pull request by bblatnick32**
This is fix for https://github.com/mempool/mempool/issues/948#issue-1059414681

### CODE REVIEW

**Comment by wiz** [comment]
Thanks for the PR. Still waiting for @softsimon's review, but in the meantime would you mind rebasing onto current master and fixing the merge conflicts so we can run the cypress test suite, and also please sign our CLA

**Comment by bblatnick32** [comment]
@wiz Thanks wiz.  By the way, are you still looking to hire a mempool dev?

**Comment by wiz** [comment]
We filled the position at the beginning of the year, but we are always looking for shadowy super coders that want to work on mempool

**Comment by bblatnick32** [comment]
@wiz For pay or for free?

**Comment by wiz** [comment]
If someone consistently makes good PRs then we would consider making an offer to hire them on a part-time or full-time basis.

**Comment by bblatnick32** [comment]
@wiz Thanks.  Happy to help.

**Pull request closed without merging**
