### PR TITLE
Moving Docs and Faq to separate lazy loaded module

### PR DESCRIPTION
**Pull request by softsimon**
This moves the **~200 kB** (uncompressed) Docs and Faq module to a separate lazy loaded module to improve the main bundle size.

### CODE REVIEW

**Review by wiz — APPROVED** [review]
Partially tested ACK @ v2.4.0-dev [2fc45380]

Seems to work fine but I want to compare the before and after loading resources and transfer size a bit more before merging to verify it's working as intended

**Comment by wiz** [comment]
@softsimon looks good, can you do this for other pages as well? also please rebase

**Review by hunicus — APPROVED** [review]
All looks to be functional. Noticing a ~300kb docs resource being loaded upon navigating to the docs section from elsewhere.

ACK from my end.

**Comment by wiz** [comment]
@hunicus since you moved the docker docs back to its original location, will need to update the FAQ link as well now - cc @knorrium for lulz

**Pull request merged**
