### PR TITLE
Add new production installation script and related files

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Comment by Emzy** [comment]
```
+zsh:1092> echo '[*] Configuring Bitcoin Signet RPC credentials in electrs start script'
[*] Configuring Bitcoin Signet RPC credentials in electrs start script
+zsh:1093> osSudo root sed -i .orig s/__ELEMENTS_RPC_USER__/eb3e1265e001f1fb59723bba52213ed3/ /elements/electrs/electrs-start-liquid
+osSudo:2> SUDO_USER=root 
+osSudo:3> shift
+osSudo:4> case FreeBSD (FreeBSD)
+osSudo:6> sudo -H -i -u root sed -i .orig s/__ELEMENTS_RPC_USER__/eb3e1265e001f1fb59723bba52213ed3/ /elements/electrs/electrs-start-liquid
sed: /elements/electrs/electrs-start-liquid: No such file or directory
```

**Comment by wiz** [comment]
Need to fix tags for bitcoin and elements repos, currently they build master despite the correct variable being set at the top

**Comment by wiz** [comment]
electrs is putting stuff in `/bitcoin/electrs/testnet` instead of `/electrs/testnet`

**Comment by wiz** [comment]
missing zfs filesystems for bitcoin signet and elements liquidtestnet

**Comment by wiz** [comment]
need electrs patch to disable compression

**Comment by wiz** [comment]
Need to use elements-0.18.1.13

**Comment by wiz** [comment]
@emzy could you please test this script after doing a clean install of the documented mempool.space OS installation procedure? for this milestone it should prepare bitcoind for mainnet, testnet, signet, and elementsd for liquid and liquidtestnet, all on separate zfs filesystems with proper configuration - please note while the mempool repos are prepared for those networks they are missing the final configurations, and nginx configuration is also not installed yet - i will work on this together with you later

**Review by Emzy — APPROVED** [review]
Tested ACK.

Only problem is that "dialog" crashes with: "Can't make sub-window at (34,103), size (69,64)." if your screen has to many lines and/or characters.

**Comment by Emzy** [comment]
electrs liquidtestnet is missing the replacement of "__ELECTRS_DATA_ROOT__", "__ELEMENTS_RPC_USER__" and  "__ELEMENTS_RPC_PASS__"
```
target/release/electrs -vv --asset-db-path /elements/asset_registry_testnet_db --address-search --cors * --db-dir __ELECTRS_DATA_ROOT__ --network liquidtestnet --daemon-dir /elements --http-addr [::]:3004 --cookie __ELEMENTS_RPC_USER__:__ELEMENTS_RPC_PASS__ --precache-scripts /elements/electrs/contrib/popular-scripts.txt
```

**Review by Emzy — APPROVED** [review]
Tested ack
Works.

**Pull request merged**
