### PR TITLE
Very basic desktop notifications implementation

### PR DESCRIPTION
**Pull request by tomat**
Minimum viable implementation

Probably needs:

- [x] Tweak the source English strings and add i18n tags
- [x] Maybe centralize notification API for re-use
- [x] Better placement of button
- [x] Actually design the button or make it not a button or whatever

For now hides notification when tab becomes visible, and does not send notifications if the tab is already visible. Does not ask any permissions until button is pressed. Browsing away from the address page will disable notifications.

### CODE REVIEW

**Comment by wiz** [comment]
Cool. For starters we probably want to tweak the source English strings and add i18n tags

**Comment by tomat** [comment]
I assume I don't need to regenerate the xlf files myself? Got a bunch of unrelated diffs there when running `i18n-extract-from-source` 😄

**Comment by tomat** [comment]
Should be good to go, seems "desktop notifications" is the canonical term so went with that

**Comment by wiz** [comment]
Closing due to stalled, can re-open this again in the future if necessary

**Pull request closed without merging**
