### PR TITLE
Add mark line to mempool chart.

### LINKED ISSUE #844: Chart: (Re)add the vertical dashed line at 1 MvB
When users are in inverted graph mode, a white dash line should indicate the 1 MvB level. 

We don't want people to have to draw it them selves like this: https://twitter.com/murchandamus/status/1443239923033726980

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
Fix #844.

### Avanced template
image

### Widget template
image

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
NACK - line should only be visible when chart is inverted

This is good:
Screen Shot 2021-10-01 at 3 52 49

This is bad:
Screen Shot 2021-10-01 at 3 57 01

**Comment by softsimon** [comment]
What wiz said but opposite. Only when the higher fee starts from the bottom the line works and makes sense.

Also the white line has different color/shading from the transaction per second graph which is more visible on the dashboard. It should look the same.

**Comment by MiguelMedeiros** [comment]
### Tasks
- [x] Fix dotted line style at transaction chart.
- [x] Remove dotted line from inverted mempool chart.

### Preview
inverted-line

**Review by wiz — APPROVED** [review]
Tested ACK @ 5c9d44e9

**Pull request merged**
