### PR TITLE
Fix liquid infinite scrolling

### PR DESCRIPTION
**Pull request by nymkappa**
Example

image

### CODE REVIEW

**Comment by softsimon** [comment]
This positioning doesn't look good. The missing fee span should just be empty but block the same space, alternatively show a "-". 

Screenshot 2023-02-21 at 13 19 52

**Comment by wiz** [comment]
That's an outdated screenshot, as of the current commit it looks like this:
Screenshot 2023-02-21 at 18 22 06

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[b2162130](https://github.com/mempool/mempool/commit/b2162130)]

**Comment by softsimon** [comment]
How about this. To not have a complete empty space.

Screenshot 2023-02-21 at 13 25 15

**Comment by wiz** [comment]
umm that's literally the bug we are fixing with this PR? lol

**Pull request merged**
