### PR TITLE
Audit data synchronization

### LINKED ISSUE #3876: feature request: import missing block template / health data from other trusted nodes
disabled by default in backend configuration
enabled in production configurations

create service that checks if block templates for old blocks are NULL

if NULL, query backend configuration's array of trusted servers (nodeXXX.YYY.mempool.space) except ours (use os local hostname to exempt ourself) to see if any other servers have a valid block template

if other nodes have valid data, import that into local database

Screenshot 2023-06-17 at 22 22 49

### PR DESCRIPTION
**Pull request by mononaut**
_(builds on #3881)_

This PR resolves #3876 and partially implements #2831 by adding a new service to the indexer which periodically checks for missing audits/templates, and imports copies from a set of trusted servers.

The service is configured with:
```
"REPLICATION": {
  "ENABLED": true,
  "AUDIT": true,
  "AUDIT_START_HEIGHT": 774000,
  "SERVERS": [
    "node201.fmt.mempool.space",
    ...
    "node206.tk7.mempool.space"
  ]
}
```

Replication is off by default, but this PR enables it in mainnet production config with the full set of `nodeXXX.YYY.mempool.space` trusted mempool servers.

---

For each block from `AUDIT_START_HEIGHT` with missing audit data, the service queries each trusted server (except itself) until it finds a valid template & audit. The first server queried is randomized to ensure requests are evenly distributed.

If data for a particular block is not available from any server, we skip that block on subsequent runs to avoid repeatedly asking for audits we know don't exist.

### CODE REVIEW

**Comment by softsimon** [comment]
Perhaps add a log output in the `$saveAuditData` showing which block height we stored and from which server we synchronized the data from

**Review by softsimon — APPROVED** [review]
tested ACK @ [19fd5ef7]

Works great! Would just be good with a debug output described above.

**Comment by mononaut** [comment]
rebased, fixed an issue that skipped some audits, and added a debug log to show which audits were imported from which server.

**Review by softsimon — APPROVED** [review]
tested ACK @ [1abd2a23c]

```
Jul 14 18:52:38 [14472] INFO: Imported audit data from node201.tk7.mempool.space for block 798184 (000000000000000000048d034829171175a63ae76b6e67e8ac3b7ece4c2e42fd)
Jul 14 18:52:38 [14472] INFO: Imported audit data from node205.tk7.mempool.space for block 798181 (0000000000000000000144ece337533508258df587dcabe88755413af820edcb)
Jul 14 18:52:38 [14472] INFO: Imported audit data from node202.tk7.mempool.space for block 798178 (000000000000000000031a71142292538a33dc319720227e50db927228ea9d34)
```

**Pull request merged**
