### PR TITLE
[audit] warn if we cannot save templates and remove exception re-throw

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/3763

### CODE REVIEW

**Review by mononaut — APPROVED** [review]
Tested ACK @ v2.6.0-dev [f95c16a7]

It might be worth making the same change for the `BlocksAuditsRepository.$saveAudit` function, since we also call that without an await in `$handleNewBlock`.

**Comment by softsimon** [comment]
> It might be worth making the same change for the `BlocksAuditsRepository.$saveAudit` function, since we also call that without an await in `$handleNewBlock`.

@nymkappa is this something you want to do in this same PR before we merge?

**Comment by nymkappa** [comment]
> > It might be worth making the same change for the `BlocksAuditsRepository.$saveAudit` function, since we also call that without an await in `$handleNewBlock`.
> 
> @nymkappa is this something you want to do in this same PR before we merge?

Done.

There are few other instances of this issue here and there in the code. So another PR will be needed to clean up all the uncaught re-throw.

**Review by softsimon — APPROVED** [review]
ACK

**Pull request merged**
