### PR TITLE
[LN] Add `as_organization` in nodes table

### PR DESCRIPTION
**Pull request by nymkappa**
Screen Shot 2022-07-12 at 12 12 55 PM

### CODE REVIEW

**Comment by softsimon** [comment]
I added `as_number` in the nodes table so that we can add additional information for the specific AS in the `geo_names` to not repeat name strings. Maybe add a new "type" in the geo_names table instead?

**Comment by nymkappa** [comment]
> I added `as_number` in the nodes table so that we can add additional information for the specific AS in the `geo_names` to not repeat name strings. Maybe add a new "type" called `organization` in the geo_names table instead?

Isn't this table used for translatable fields?

**Review by softsimon — APPROVED** [review]
utACK

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[3d2ff7ef](https://github.com/mempool/mempool/commit/3d2ff7ef)]
```
root@localhost [mempool_mainnet_lightning]> select * from geo_names where id = 397444;
+--------+-----------------+----------+
| id     | type            | names    |
+--------+-----------------+----------+
| 397444 | as_organization | "AS-OKI" |
+--------+-----------------+----------+
1 row in set (0.000 sec)
```

**Pull request merged**
