### PR TITLE
Dual-license mempool under both the GNU AGPLv3 and GPLv3 licenses

### PR DESCRIPTION
**Pull request by wiz**
A few weeks ago in #388, we changed the license for the mempool project from MIT+CC to AGPLv3. This was generally met with very positive feedback from the Bitcoin community. However, a few very large enterprise organizations that love the mempool project are now no longer able to use our code, since apparently some enterprise organizations have an internal policy of not using AGPL licensed software.

Since the AGPLv3 license is compatible with the GPLv3 license in various ways, adding the GPLv3 as an alternative second license for the project seems like a reasonable way to retain most of the copyleft properties of our current AGPLv3 license, while also keeping the community happy and allowing them GPLv3 as another choice if they are prohibited from using the AGPL internally.

Therefore, I propose to add GPLv3 as an alternative license for the mempool open source project in this PR. If you are okay with this, please ACK with "I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses"

From the list on https://github.com/mempool/mempool/graphs/contributors

- [x] @softsimon (640 commits)
- [x] @wiz (271 commits)
- [x] @bguillaumat (15 commits)
- [x] @TechMiX (11 commits)
- [ ] @rbrooklyn (7 commits)
- [x] @junderw (5 commits)
- [x] @andrerfneves (2 commits)
- [x] @andrewtoth (2 commits)
- [x] @6102bitcoin (1 commit)
- [x] @Czino (1 commit)
- [x] @devinbileck (1 commit)
- [x] @knorrium (1 commit)
- [x] @jambolo (1 commit)
- [ ] @lucasmoten (1 commit)
- [x] @fiatjaf (1 commit)
- [x] @pox (1 commit)
- [x] @RandyMcMillan (1 commit)
- [ ] @timlucmiptev (1 commit)

### CODE REVIEW

**Comment by wiz** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by junderw** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

--- 

I think that anti-AGPL sentiment in general is bullshit, though.

**Comment by andrewtoth** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by devinbileck** [comment]
ACK. I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses

**Comment by softsimon** [comment]
ACK. I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by bguillaumat** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by pox** [comment]
ACK
I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses

**Comment by RandyMcMillan** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by andrerfneves** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by jambolo** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses

**Comment by knorrium** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by Czino** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by fiatjaf** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by lucasmoten** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Comment by rbrooklyn** [comment]
ACK - I hereby re-license my contributions to the mempool open source project under both the GNU AGPLv3 and GPLv3 licenses.

**Pull request merged**
