### PR TITLE
Add border to qr code because it's a best practice

### PR DESCRIPTION
**Pull request by nymkappa**
image

### CODE REVIEW

**Comment by wiz** [comment]
my hero

**Review by softsimon — APPROVED** [review]
tested ACK @ v2.5.0-dev [[273770a63](https://github.com/mempool/mempool/commit/273770a63)]

**Comment by wiz** [comment]
there is already a border on the address page, so if you're adding a border on the QR code component then we should remove the border on the address page

**Comment by nymkappa** [comment]
Okay so the css is weird. Therefore in order to avoid breaking all the things I just added a `border` parameter in the qr code component that I can use in other places in the future.

Rebased on top of master.

**Review by softsimon — APPROVED** [review]
tested ACK @ v2.5.0-dev [[6f68c1666](https://github.com/mempool/mempool/commit/6f68c1666)]

**Pull request merged**
