### PR TITLE
scroll to see all mempool blocks

### PR DESCRIPTION
**Pull request by mononaut**
This PR makes the blockchain bar scrollable in both directions, so that we can display the full set of projected mempool blocks even on smaller screens and mobile devices.

https://github.com/mempool/mempool/assets/83316221/340dd669-4873-4d06-b87e-daa93df00f8e

other uses of these components are unaffected (TV view, docs/faq, clocks etc).

making this work nicely with the flip-blockchain-direction animation is tricky, and maybe depends on browser quirks, ~~so I'm leaving this in draft while I verify that the current solution works on other browsers and devices.~~

### CODE REVIEW

**Comment by mononaut** [comment]
yes, very good point. I'll try to implement that.

**Comment by mononaut** [comment]
the relevant block is now automatically scrolled into view when selecting a mempool block or an unconfirmed transaction:

https://github.com/mempool/mempool/assets/83316221/699d8e3c-2560-4f8b-aebb-52e30ca1f5ff

**Comment by mononaut** [comment]
taking this out of draft now that I've tested across several browser/device combinations.

**Comment by nymkappa** [comment]
Fixes https://github.com/mempool/mempool/issues/3888

**Review by softsimon — APPROVED** [review]
tested ACK @ [58b805]

But not sure everyone in the team agree of this change.

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.6.0-dev [efcb58a4a]

I think this is great, and I would even suggest considering to take the idea further to make the mempool scrolled over a bit by default on the mempool dashboard, and the blockchain scrolled over a bit by default on the blockchain dashboard, but this could be a stupid idea :)

Screenshot 2023-07-05 at 9 28 56
Screenshot 2023-07-05 at 9 29 13

**Pull request merged**
