### PR TITLE
Add nodes per country table page

### PR DESCRIPTION
**Pull request by nymkappa**
This PR adds a very simple page to browser a list of nodes per country (no pagination). You can access it via the following url `/lightning/nodes/country/:country`.

For example `/lightning/nodes/country/france` or `/lightning/nodes/country/sweden`

Screen Shot 2022-07-16 at 3 57 43 PM
Screen Shot 2022-07-16 at 3 58 48 PM

Screen Shot 2022-07-16 at 3 56 48 PM
Screen Shot 2022-07-16 at 3 59 04 PM

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
Need a matching /graphs page pie chart for "Lightning nodes per country" with a table where clicking on a pie slice country goes to this page. Also the URL should use the 2 letter country code like US or DE or JP

**Comment by nymkappa** [comment]
> Need a matching /graphs page pie chart for "Lightning nodes per country" with a table where clicking on a pie slice country goes to this page. Also the URL should use the 2 letter country code like US or DE or JP

Fixed in https://github.com/mempool/mempool/pull/2098/commits/93e93d44f4b607178b4c80fffc738c073c7a510c
You can now access the list using country codes, for example `/lightning/nodes/country/us`

**Review by softsimon — APPROVED** [review]
code looks good

utACK

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[93e93d44](https://github.com/mempool/mempool/commit/93e93d44)]

**Pull request merged**
