### PR TITLE
Display missing taproot inner script

### LINKED ISSUE #973: Missing P2TR witness scripts
### Description

Unlike P2SH and P2WSH, P2TR spends (specifically script path spends) don't show the spending script.

### Steps to reproduce

Go to transaction 905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530 on mainnet ([link](https://mempool.space/tx/905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530)), expand the details of inputs and outputs and check the one input.

If I read [BIP 341](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki#script-validation-rules) correctly this is a Taproot script path spend and the script (second to last witness element) decodes to:
```
febe583fa77e49089f89b78fa8c116710715d6e40cc5f5a075ef1681550dd3c4 OP_CHECKSIGVERIFY
d0fa46cb883e940ac3dc5421f05b03859972639f51ed2eccbf3dc5a62e2e1b15 OP_CHECKSIG
```

As you can see, this script isn't shown anywhere in the details.

### Screenshots

p2tr

### PR DESCRIPTION
**Pull request by softsimon**
fixes #973

This PR reveals the inner spending script on a taproot transaction.
This does _only_ fix the missing spend script for the backend when running `bitcoind` and not when using `esplora` as blockstream/electrs needs to implement this natively just like with other output types.

Some open questions remains to be tested/answered:
* Will this work on all types of Taproot-transactions
* Should it be called `P2WSH witness script`?

**Before:**
Screen Shot 2021-12-05 at 23 54 10

**After:**

Screen Shot 2021-12-05 at 23 54 34

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
NACK @ 10a110e6
Newly added data is not visible using TXID in referenced bug report: https://node206.mempool.space/tx/905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530

**Comment by softsimon** [comment]
> NACK @ [10a110e](https://github.com/mempool/mempool/commit/10a110e682d5db7b438708bd6453998682ea529b) Newly added data is not visible using TXID in referenced bug report: https://node206.mempool.space/tx/905ecdf95a84804b192f4dc221cfed4d77959b81ed66013a7e41a6e61e7ed530

It's not supposed to work with blockstream/electrs as backend which the PR states.

**Comment by wiz** [comment]
Sorry, misunderstood that part. But okay in that case I can just merge it untested since the change looks quite minimal and safe and doesn't cause any issues on the production backend that I can see.

**Review by wiz — APPROVED** [review]
utACK

**Pull request merged**
