### PR TITLE
Show miner name on block timeline

### PR DESCRIPTION
**Pull request by BitcoinMechanic**
This will display the name of a miner who creates their own templates. 
image

### CODE REVIEW

**Review by softsimon — CHANGES_REQUESTED** [review]
It looks OK but we need to remove the "on" text label.

A text label may or may not work on all 30+ languages due to various reasons. Just the fact that it needs to be translated is a hurdle.

So try removing the label completely. On the block page it might look good adding / or @ or something. Like. Steve @ OCEAN

**Review by mononaut — APPROVED** [review]
Tested ACK @ [81ddce2]

**Review by softsimon — APPROVED** [review]
partial tested ACK

**Comment by wiz** [comment]
Is there a testcase for this? i.e. please tell me a block height that has the extra data in it

**Comment by BitcoinMechanic** [comment]
https://mempool.space/testnet/mining/pool/ocean

**Pull request merged**
