### PR TITLE
Add VA1 mempool.space lightning node pubkeys

### PR DESCRIPTION
**Pull request by wiz**

### CODE REVIEW

**Review by nymkappa — APPROVED** [review]
Tested ACK @ 38d30d23e5eb8c3ca40f9a0969620daa7558ec13 but they do not show in my graph yet. Syntax is okay.

**Review by TokenPayId — COMMENTED** [review]
wiz/add-va1-mempoolspace-lightning-nodes

**Comment by Josemoe** [comment]
I'm new  here and would like to know more about block rewards and how to
access them it's been like ten months since I seen the block

**Comment by Josemoe** [comment]
> wiz/add-va1-mempoolspace-lightning-nodes

Thanks

**Pull request merged**
