### PR TITLE
Liquid Audit dashboard: requested changes

### PR DESCRIPTION
**Pull request by natsoni**
This PR: 
- includes the number of UTXOs held by the Federation instead of the monthly address change:
Screenshot 2024-02-09 at 16 39 08

- Updates `BTC Reserves` -> `BTC Holdings`, `Peg-O-Meter` -> `Assets vs Liabilities`, and prints a percentage instead of a ratio
Screenshot 2024-02-09 at 16 40 50

- cleans up other minor things like skeleton loaders in tables, some margins in widgets and fixes the Liquid navbar for small screens. 

TODO: 
- [x] Improve the pegs table pagination and allow to query pegs up to the first ones
- [x] migrate the audit dashboard to the main page
- [ ]  ~clean up the main dashboard from all the Liquid stuff~

### CODE REVIEW

**Comment by natsoni** [comment]
Main Liquid dashboard:

Screenshot 2024-02-13 at 00 59 57

**Comment by softsimon** [comment]
> Main Liquid dashboard:

The graphs can switch place with the top data stuff remain the same. 
I don't like the "Peg historical data" title but not sure what is better...

**Comment by natsoni** [comment]
> The graphs can switch place with the top data stuff remain the same. I don't like the "Peg historical data" title but not sure what is better...

Screenshot 2024-02-13 at 09 36 37

**Review by softsimon — APPROVED** [review]
tested ACK @ [d55d5db0]

**Pull request merged**
