### PR TITLE
Add graph download feature

### PR DESCRIPTION
**Pull request by nymkappa**
Should we offer this feature on mobile layout as well? It works, but the result may not be as good as desktop, also have some UX issue with legends and things like that, right now it's enabled on all screen size, play around with it and let me know 👍🏻 

Clicking on the download button next to the graph title automatically download the chart screenshot.

Screen Shot 2022-05-05 at 5 53 03 PM

Output examples

#### Desktop

block-fee-rates-3y-1651740786
pools-dominance-all-1651741055

#### Mobile portrait

block-fee-rates-3y-1651740865

_Note here the missing legends due to small screen width._

pools-dominance-3y-1651740982

#### Mobile landscape

block-fee-rates-3y-1651740884
pools-dominance-3y-1651740976

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ v2.4.0-dev [[f55bc0cb](https://github.com/mempool/mempool/commit/f55bc0cb)]

Thanks for adding this, but I found a few issues:

1) Graphs now have different background colors:
Screen Shot 2022-05-06 at 14 47 21
Screen Shot 2022-05-06 at 14 47 48

2) Image files downloaded are missing .svg filename extension:
Screen Shot 2022-05-06 at 14 49 45
Screen Shot 2022-05-06 at 14 49 34

3) Download button placement needs polishing
Screen Shot 2022-05-06 at 14 48 55

**Comment by nymkappa** [comment]
> Tested NACK @ v2.4.0-dev [[f55bc0cb](https://github.com/mempool/mempool/commit/f55bc0cb)]
> 
> Thanks for adding this, but I found a few issues:
> 
>     1. Graphs now have different background colors:
> 
> 
> Screen Shot 2022-05-06 at 14 47 21
> 
> Screen Shot 2022-05-06 at 14 47 48
> 
>     2. Image files downloaded are missing .svg filename extension:
> 
> 
> Screen Shot 2022-05-06 at 14 49 45
> 
> Screen Shot 2022-05-06 at 14 49 34
> 
>     3. Download button placement needs polishing
> 
> 
> Screen Shot 2022-05-06 at 14 48 55

Fixed in https://github.com/mempool/mempool/pull/1601/commits/84e069e1e7248f36624d5832720bbe478fa5891a

**Comment by wiz** [comment]
Please rebase onto current master

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.4.0-dev [[1988769c](https://github.com/mempool/mempool/commit/1988769c)]

**Pull request merged**
