### PR TITLE
INDEX 'added' in statistics table

### PR DESCRIPTION
**Pull request by nymkappa**

### CODE REVIEW

**Review by softsimon — APPROVED** [review]

**Comment by softsimon** [comment]
utACK

**Review by wiz — APPROVED** [review]
NACK @ 1e78326ee4e53f6e35ad22f80431388d1ebd3626
```
/mempool/mainnet/backend/dist/index.js:81
                throw new Error(e instanceof Error ? e.message : 'Error');
                      ^

Error: Duplicate key name 'added'
    at Server.startServer (/mempool/mainnet/backend/dist/index.js:81:23)
```

**Review by wiz — CHANGES_REQUESTED** [review]
NACK @ 1e78326
```
/mempool/mainnet/backend/dist/index.js:81
                throw new Error(e instanceof Error ? e.message : 'Error');
                      ^

Error: Duplicate key name 'added'
    at Server.startServer (/mempool/mainnet/backend/dist/index.js:81:23)
```

**Review by wiz — APPROVED** [review]
Tested ACK @ 0e6cc67c0a44637a42cb9c8c1b8b02f6ad16745c

**Pull request merged**
