### PR TITLE
New concept for dashboard layout components.

### LINKED ISSUE #468: New UI/UX responsive layout.
### Description

A new concept of responsive design for the dashboard components.

- [x] Recomended fees
- [x] Dificult adjustment
- [x] Memory usage
- [x] Incomming transactions
- [x] Latest Blocks
- [x] Latest Transactions
- [x] Block component
- [x] Transaction component
- [x] Address component
- [x] About Page
- [x] TV Page
- [x] Graph Page

The idea is to make the elements more organized, taking up less space on the screen.

### Steps to reproduce

Open the website at the `homepage` and resize your screen to watch the dashboard components change to adapt responsive layouts.

### Expected behaviour

https://user-images.githubusercontent.com/5798170/115462948-a1e8fd00-a201-11eb-9483-ba3edc852ad5.mp4

### Actual behaviour

https://user-images.githubusercontent.com/5798170/115462972-a7464780-a201-11eb-8e70-2c882ea714ce.mp4

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
Fix #468

### CODE REVIEW

**Review by jaonoctus — APPROVED** [review]

**Comment by softsimon** [comment]
The issues left I have found is:

- [ ] Everywhere the fiat price is listed `(<app-fiat` it should break to next row and remove the () parenthese design. For example on the Transaction page (fee) and Mempool block
- [ ] The "1 confirmation" button on transaction page is smaller than it should be.

**Comment by MiguelMedeiros** [comment]
Found an issue:
- [ ] I've found a few more `(<app-fiat` on bisq components.

**Comment by softsimon** [comment]
- [ ] Mempool blocks component needs to use the new way of displaying fiat as well, with break row on mobile
- [ ] Prices should not break row on desktop, (Transaction page, and transactions list)
- [ ] Transaction ID should be left aligned



Screen Shot 2021-04-29 at 18 54 14

Screen Shot 2021-04-29 at 18 52 33

Screen Shot 2021-04-29 at 18 52 30

Screen Shot 2021-04-29 at 18 52 19

**Comment by softsimon** [comment]
Tested ACK

**Pull request merged**
