### PR TITLE
Move difficulty adjustment code to separate module

### PR DESCRIPTION
**Pull request by nymkappa**
Split difficulty adjustment code into a separate module so we can re-use it in the mining dashboard

### CODE REVIEW

**Comment by wiz** [comment]
Why is the difficulty adjustment code in the frontend at all?
Shouldn't it be in the backend and exposed by the websocket and REST APIs ?

**Comment by nymkappa** [comment]
> Why is the difficulty adjustment code in the frontend at all? Shouldn't it be in the backend and exposed by the websocket and REST APIs ?

I agree. This would be an useful API endpoint for mining service providers and miners.

**Comment by wiz** [comment]
I suppose it just needs to be added to the websocket since the REST API endpoint exists at https://mempool.space/testnet/api/v1/difficulty-adjustment

Did you want to close this PR and do that instead? I don't see why there is a totally duplicate implementation of the difficulty adjustment code in the frontend at all, unless there is some reason I am missing? @softsimon

**Review by softsimon — APPROVED** [review]
tested ACK @ fcca9113

**Pull request merged**
