### PR TITLE
Fix path for newsyslog configs in prod installer

### PR DESCRIPTION
**Pull request by Emzy**

### CODE REVIEW

**Review by wiz — APPROVED** [review]
utACK - looks good but not sure if `newsyslog -C` works on linux

**Comment by Emzy** [comment]
> utACK - looks good but not sure if `newsyslog -C` works on linux

fixed in da4e6fc

**Comment by Emzy** [comment]
Added Debian rsyslog configuration.

**Review by wiz — APPROVED** [review]
utACK

**Pull request merged**
