### PR TITLE
High contrast theme

### PR DESCRIPTION
**Pull request by mononaut**
This PR:
 - Consolidates various hard-coded CSS colors into CSS variables.
 - Adds a theme service which can dynamically load a stylesheet to override these variables, and also swap out javascript-defined colors in a few places.
 - Implements a high-contrast/colorblind-friendly theme
 - Adds a dropdown at the bottom of the main dashboard page to switch between the default and high contrast themes.
 
So far, the new high contrast theme increases the contrast of some common UI elements, and swaps the red-green fee rate gradient in the block visualizations for a more colorblind-friendly blue-orange.

Comparison of the original default theme and the high contrast colorblind-friendly theme:
| | Default Theme | High Contrast |
|-|-|-|
| normal appearance | default-actual | highcontrast-actual |
| simulated deuteronopia (green-blindness) | default | highcontrast |

### CODE REVIEW

**Comment by wiz** [comment]
@TheBlueMatt wdyt?

**Comment by wiz** [comment]
@softsimon any reason why this was never merged?
@natsoni did you want to fix this up?

**Comment by wiz** [comment]
Replaced by #4904

**Comment by softsimon** [comment]
Replaced by https://github.com/mempool/mempool/pull/4916

**Pull request closed without merging**
