### PR TITLE
Pixel-aligned grids for sharper block visualizations

### PR DESCRIPTION
**Pull request by mononaut**
This PR clamps size of the block visualization component to multiples of the grid resolution, and adjusts the grid padding to ensure squares are always pixel-aligned without any fuzzy anti-aliasing effects.

For example, with a grid resolution of 75x75, the component can be 75px, 150px, 225px, 300px, 375px, 425px, 500px wide etc.

The implementation relies on CSS grids, but falls back gracefully to the old behavior where that's not supported.

The tradeoff of constraining the possible sizes of the visualization like this is that the visualization can look too small at some screen breakpoints.

To mitigate this, the PR also boosts the grid resolution from 75x75 to 80x80 squares, which better matches the current responsive width on the most common screen sizes.

This applies to the block pages, block previews, and mempool-block pages.

| Before | After |
|-|-|
| Screenshot 2023-04-02 at 6 59 12 AM | Screenshot 2023-04-02 at 6 58 52 AM |
| before | after |

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
It seems there are a lot of tradeoffs with this PR, how about we set it as draft for now and discuss later

**Comment by mononaut** [comment]
Rebased on current master and adjusted sizes and resolutions slightly to improve default layouts on large-ish screens:

| Before | After |
|-|-|
| Screenshot 2023-07-14 at 3 04 37 PM | Screenshot 2023-07-14 at 3 04 46 PM |
| Screenshot 2023-07-14 at 3 05 15 PM | Screenshot 2023-07-14 at 3 04 59 PM |
| Screenshot 2023-07-14 at 3 05 29 PM | Screenshot 2023-07-14 at 3 06 23 PM |

**Comment by mononaut** [comment]
rebased again again

**Review by softsimon — APPROVED** [review]
tested ACK @ [94fe8e699]

I like it now. Much sharper and the changes in margins in certain browser widths are worth it.

@wiz needs to approve this as well.

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.6.0-dev [9a6565cd9]

**Review by wiz — APPROVED** [review]
Tested ACK @ v3.0.0-dev [8680e5f06]

**Pull request merged**
