### PR TITLE
reconnect websocket after closed by server

### PR DESCRIPTION
**Pull request by mononaut**
PR #3704 forcibly disconnects websocket clients that misbehave. This PR changes the frontend reconnection logic to always establish a fresh websocket instead of trying to revive the old one, which seems to fix the issue.

### CODE REVIEW

**Comment by softsimon** [comment]
Closing due to not being something need fixing currently after talking with @mononaut

**Comment by wiz** [comment]
hey @softsimon we need this can we re-open and merge it

**Comment by mononaut** [comment]
rebased on current master

**Review by softsimon — APPROVED** [review]
tested ACK @ [12cf130c00]

Although I don't think we reused the websocket before, as we instantiated a new object, this PR just more cleanly shut down the previous one before opening the new.

**Pull request merged**
