### PR TITLE
Move all charts into /graphs page

### PR DESCRIPTION
**Pull request by nymkappa**
This PR merges all charts into the /graphs page. All charts can be access through the menu at the top left of the page.

### Screenshots
image
image
image
image

### CODE REVIEW

**Comment by nymkappa** [comment]
Let's discuss about this again next week (TM)

**Comment by wiz** [comment]
@nymkappa tomorrow when you get in please fix the merge conflicts and rebase onto master so we can play around with this to discuss with @softsimon

**Review by softsimon — APPROVED** [review]
tested ACK

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.4.0-dev [[8e61720e](https://github.com/mempool/mempool/commit/8e61720e)]

**Pull request merged**
