### PR TITLE
Improve precision of fee distribution chart labels

### LINKED ISSUE #4311: decimals to 1-2 sats?
image

There's currently 123mb is transaction between 1 sat and 1.5 sat 

Could we see decimals below 2sat?

### PR DESCRIPTION
**Pull request by mononaut**
Resolves #4311, by increasing the precision of fee rate labels in the fee distribution chart to 3 significant figures (or at least integer precision).

This PR also adds a small top margin to the chart to improve legibility.

| Before | After |
|-|-|
| Screenshot 2023-10-15 at 11 34 49 PM | Screenshot 2023-10-15 at 11 34 12 PM |
| Screenshot 2023-10-15 at 11 34 42 PM | Screenshot 2023-10-15 at 11 34 17 PM |

### CODE REVIEW

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by softsimon** [comment]
On mobile it becomes a bit tight. Any suggestion on solution?

Old vs new

Screenshot 2023-11-11 at 14 46 59
Screenshot 2023-11-11 at 14 47 02

**Comment by mononaut** [comment]
maybe if we hide the scale on the left side on very narrow screens that would free up enough space?

**Comment by mononaut** [comment]
how's this?

localhost_4200_mempool-block_0(iPhone SE)

(on screens <450px wide, hide the left axis, expand the graph into that space, and slightly reduce the data label font size)

**Comment by mononaut** [comment]
Implemented that change, and rebased on current master

**Review by softsimon — APPROVED** [review]
tested ACK @ [37605d57]

**Pull request merged**
