### PR TITLE
[lightning] add taproot-channels to node features

### PR DESCRIPTION
**Pull request by starius**
Update from https://github.com/lightningnetwork/lnd/blob/master/lnwire/features.go

Currently the feature is displayed as "unknown" if a node has it:

https://mempool.space/testnet/lightning/node/038863cf8ab91046230f561cd5b386cbff8309fa02e3f0c3ed161a3aeb64a643b9

Screenshot 2023-10-13 at 14-14-49 Node aranguren org

### CODE REVIEW

**Comment by starius** [comment]
Hi @TheBlueMatt !  Thank you for review! What are my next steps? I tried to accept CLA, but CI is still failing.

**Comment by softsimon** [comment]
> Hi @TheBlueMatt ! Thank you for review! What are my next steps? I tried to accept CLA, but CI is still failing.

Ignore the CLA warning. It's there so it's fine :)

**Comment by softsimon** [comment]
Mainnet node to try on https://mempool.space/lightning/node/03f10c03894188447dbf0a88691387972d93416cc6f2f6e0c0d3505b38f6db8eb5

**Review by softsimon — APPROVED** [review]
tested ACK @ [562cd5683]

Tested with LND

**Pull request merged**
