### PR TITLE
Align dashboards

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/2499

Lightning dashboard now matches other dashboard overall layout

image

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ v2.5.0-dev [[4e55f532](https://github.com/mempool/mempool/commit/4e55f532)]

Screenshot 2023-02-23 at 19 31 59

**Comment by nymkappa** [comment]
> Tested NACK @ v2.5.0-dev [[4e55f532](https://github.com/mempool/mempool/commit/4e55f532)]
> 
> 
> 
> Screenshot 2023-02-23 at 19 31 59
> 
> 

Mobile landscape?

**Comment by wiz** [comment]
I just started with a big window and resized it smaller, the layout should adapt to any width automatically

**Comment by nymkappa** [comment]
> > Tested NACK @ v2.5.0-dev [[4e55f532](https://github.com/mempool/mempool/commit/4e55f532)]
> > Screenshot 2023-02-23 at 19 31 59
> 
> Mobile landscape?

Fixed in https://github.com/mempool/mempool/pull/3116/commits/a26dc977ba0783bc6beb492741c2f1a007531e4e

**Review by softsimon — APPROVED** [review]
tested ACK @v2.5.0-dev [0929d53c5]

**Pull request merged**
