### PR TITLE
Migrate tslint to eslint and prettier

### PR DESCRIPTION
**Pull request by knorrium**
Working with `ng lint` and the VSCode ESLint plugin. The e2e suite has an additional set of rules to avoid unnecessary waits, etc.

No pre-commit hooks yet but we should add them if this is merged.

```
ng update @angular/cli --migrate-only --from 10 --to 11
ng add @angular-eslint/schematics
ng g @angular-eslint/schematics:convert-tslint-to-eslint --remove-tslint-if-no-more-tslint-targets --ignore-existing-tslint-config
npm install eslint-plugin-cypress --save-dev
npm install eslint-config-airbnb-typescript eslint-plugin-import eslint-config-prettier eslint-plugin-prettier prettier --save-dev
``` 

VSCode ESLint settings to apply the styling and fixes when saving:

```
{
    "[typescript]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": true
        },
        "editor.formatOnSave": false
      },
      "[json]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
          "source.fixAll.eslint": true
        },
        "editor.formatOnSave": false
    },
    "eslint.codeAction.showDocumentation": {
        "enable": true
    }
}
```

### CODE REVIEW

**Comment by softsimon** [comment]
This is great

**Comment by MiguelMedeiros** [comment]
Thanks @knorrium!!! :heart:

**Review by MiguelMedeiros — APPROVED** [review]

**Review by softsimon — CHANGES_REQUESTED** [review]
1. Update tsconfig.json path in `.eslintrc.rc` to handle different workspace paths
2. If possible, update linting to force or allow constructor variables on multiple lines

**Comment by knorrium** [comment]
Closing this PR to submit a multistep migration

**Pull request closed without merging**
