### PR TITLE
Upgrade bitcoin core to v25.1

### PR DESCRIPTION
**Pull request by fanquake**
Changes: https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-25.1.md.

### CODE REVIEW

**Comment by wiz** [comment]
@fanquake sorry for the late response but I'm confused, is there any reason not to merge this?

**Comment by fanquake** [comment]
@wiz this should still be merged, I couldn't figure out how to satisy the bot.
Happy for anyone else to followup.

**Comment by wiz** [comment]
yeah the bot is stupid, i can just bypass it, can you reopen?

**Review by wiz — APPROVED** [review]
utACK

**Comment by wiz** [comment]
thanks 🤙

**Pull request merged**
