### PR TITLE
[Indexing] - Support 10 blocks depth reorgs

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/1221

This is very basic implementation of reorg support for indexing.

* When we're done indexing a newly received block, we validate the chain of the past 10 indexed blocks
  * If the chain is broken, then we delete the past 10 indexed blocks, the last network hashrate daily entry and the last pools weekly  hashrate entries
  * We then re-index this data as usual
* When the node backend starts, we always re-index the previously mentioned data, in case the node went offline with a now invalid chain 

### How to test

1. Save latest indexed block hash
```mysql
MariaDB [mempool]> select height, hash from blocks order by height desc limit 1;
+--------+------------------------------------------------------------------+
| height | hash                                                             |
+--------+------------------------------------------------------------------+
| 727443 | 0000000000000000000702e1aab00e57c8727df44fe98f923429990dd273799f |
+--------+------------------------------------------------------------------+
```
2. Manually change the most recent block `blocks.hash` in the database to simulate a network fork
```mysql
MariaDB [mempool]> UPDATE `blocks` SET `hash` = '8aeaa61e5110ab6df6378cad7e9000000000004a8160b3d19230000000015314' WHERE `height` = '727443';
Query OK, 1 row affected (0.009 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [mempool]> select height, hash from blocks order by height desc limit 1;
+--------+------------------------------------------------------------------+
| height | hash                                                             |
+--------+------------------------------------------------------------------+
| 727443 | 8aeaa61e5110ab6df6378cad7e9000000000004a8160b3d19230000000015314 |
+--------+------------------------------------------------------------------+

```
3. Wait for a new block to be mined. In the log, you should see the following
  ```sh
Mar 15 13:43:29 [16547] NOTICE: Chain divergence detected at block 727444, re-indexing most recent data
Mar 15 13:43:29 [16547] DEBUG: Delete 10 most recent indexed blocks from the database
Mar 15 13:43:29 [16547] DEBUG: Delete latest hashrates data points from the database
Mar 15 13:43:29 [16547] INFO: Indexing blocks from #727444 to #0
Mar 15 13:43:30 [16547] DEBUG: Indexing 10 blocks from #727444 to #717443
Mar 15 13:43:36 [16547] INFO: Block indexing completed
Mar 15 13:43:36 [16547] INFO: Indexing network daily hashrate
Mar 15 13:43:36 [16547] INFO: Indexing mining pools weekly hashrates
Mar 15 13:43:36 [16547] INFO: Daily network hashrate indexing completed
Mar 15 13:43:36 [16547] INFO: Weekly pools hashrate indexing complete
  ```
4. Verify that the invalid block modified in step 1 has properly been re-indexed:
```mysql
MariaDB [mempool]> select height, hash from blocks where height = 727443;
+--------+------------------------------------------------------------------+
| height | hash                                                             |
+--------+------------------------------------------------------------------+
| 727443 | 0000000000000000000702e1aab00e57c8727df44fe98f923429990dd273799f |
+--------+------------------------------------------------------------------+
```

### CODE REVIEW

**Comment by nymkappa** [comment]
@wiz @softsimon I've rebased on master. I think this must be included in 2.4. Thanks.

**Comment by softsimon** [comment]
> @wiz @softsimon I've rebased on master. I think this must be included in 2.4. Thanks.

Ok will test this one soon.. Btw seems like rebase is needed again :P

**Comment by nymkappa** [comment]
> > @wiz @softsimon I've rebased on master. I think this must be included in 2.4. Thanks.
> 
> Ok will test this one soon.. Btw seems like rebase is needed again :P

Rebased

**Review by softsimon — APPROVED** [review]
tested ACK @ 271dad00

**Comment by nymkappa** [comment]
> tested ACK @ [271dad0](https://github.com/mempool/mempool/commit/271dad008cb2e70fb74f6099795e3495a6463c7b)
> 
> Need rebase to merge.

Merged. The only conflict was in `index.js` https://github.com/mempool/mempool/compare/271dad008cb2e70fb74f6099795e3495a6463c7b..90ca668bcb73811c3d2f721c2e1eace2eedd94e1#diff-c20200a666b149a045e365999f581db8e04687cfc9569bdf4c9477cab954d324

**Pull request merged**
