### PR TITLE
Updated Zeus logo

### PR DESCRIPTION
**Pull request by Bosch-0**
Updated to the new Zeus logo

### CODE REVIEW

**Review by kaloudis — APPROVED** [review]
LGTM

**Comment by wiz** [comment]
@Bosch-0 it looks like you added the stylized font for Zeus but I think you meant to use the shadowy Zeus figure instead, right?

**Comment by Bosch-0** [comment]
No the stylized logo was the intended one - the mascot is secondary branding

**Comment by Bosch-0** [comment]
Updated to use the app hand holding the bolt icon, the mascot is too detailed to be used at such a small size.

**Comment by wiz** [comment]
It looks fine on Twitter? Not sure why you want to go with this other thing when it's clearly your primary profile photo :)

image

**Comment by Bosch-0** [comment]
I pinged @kaloudis to use the hand icon for twitter, telegram, slack etc. will update those shortly.

**Comment by wiz** [comment]
@Bosch-0 ok cool but the 165KB image is a bit large, would you mind using an SVG one if available, or if not a PNG that's 400x400 size and also can you squash this branch and rebase onto current master? thanks a lot

**Review by LamarisSmiley — APPROVED** [review]

**Comment by Bosch-0** [comment]
Stuffed up my rebase sorry, here is a new PR https://github.com/mempool/mempool/pull/1316

**Pull request closed without merging**
