### PR TITLE
Add Marina Wallet as Community Integration on About page

### PR DESCRIPTION
**Pull request by wiz**
Screen Shot 2021-07-21 at 0 15 37

### CODE REVIEW

**Comment by MiguelMedeiros** [comment]
Tested ACK.

marina-icon

**Review by MiguelMedeiros — APPROVED** [review]

**Review by softsimon — CHANGES_REQUESTED** [review]
The logo is too zoomed in, inside the circle so the mermaid face is cut off.

Screen Shot 2021-07-21 at 16 30 10

The whole mermaid should be inside
Screen Shot 2021-07-21 at 16 31 34

**Comment by MiguelMedeiros** [comment]
> The logo position/size is not so great, the mermaid face is cut off.
> 
> Screen Shot 2021-07-21 at 16 30 10
> 
> The whole mermaid should be inside
> Screen Shot 2021-07-21 at 16 31 34

Good eyes, @softsimon !

We can solve this by exporting a new image with the same logo but with more padding.

**Comment by wiz** [comment]
Screen Shot 2021-07-24 at 2 47 25

**Pull request merged**
