### PR TITLE
Create docs page with faq and api docs

### PR DESCRIPTION
**Pull request by hunicus**
This pull request is the (small) start of a docs section for the Mempool site. You can see the rest of my proposal [here](https://github.com/mempool/mempool/issues/965).

Summary of changes:
- add new page at /docs for bitcoin network pages only (mainnet, testnet, and signet)
- add 'FAQ' tab (future tabs are outlined [here](https://github.com/mempool/mempool/issues/965))
- add questions and answers covering most common questions from users (gathered from surveying Telegram, GitHub, and Keybase activity from over the past few months)

Handling i18n is left for later once the direction of this /docs page is better known.

This PR was opened in draft status because it is probably not ready to merge:

#### ~1. Not tested with other networks~ (initial roll-out to mempool.ninja looked fine; more tests will be done before merging final changes)

My local mempool instance is only configured to be in mainnet mode. Obviously this doesn't matter for the FAQ content itself since it's just static text, but I can't be 100% sure if/how the `/docs` menu item will show when in testnet or signet mode.

#### ~2. Unsure about colors/design~ (solved with move to accordion)

What do you think about the colors/design? I took colors from the existing color palette, but I'm not sure they go well together.

#### ~3. FAQ link list~ ([this will be implemented](https://github.com/mempool/mempool/pull/966#issuecomment-986260855))

Should the FAQ list have a list of question at the top that allow the user to jump to the answer below? Like wikis often do?

#### 4. Curious about others' thoughts on how this FAQ page fits in with other plans

[See this issue](https://github.com/mempool/mempool/issues/965). If there are serious objections, then it might become necessary to take these changes back to the drawing board.

I'd appreciate any advice/guidance to help address the issues mentioned above.

### CODE REVIEW

**Comment by wiz** [comment]
Wow, thanks for the excellent first PR. The FAQ page looks great, please DM me on Keybase as I would like to go over the text with you. Also keep in mind since this code is served by both the official mempool.space instance and unofficial instances like mempool.bitcoin.ninja we need to wrap things like hard-coded Tor onion hostname in an "if mempool.space official" code block so it only gets displayed on the official site

**Comment by hunicus** [comment]
Working on updates per chat with wiz. 

These include:
- moving faq to accordion so that items are collapsed by default
- make faq items linkable so direct answers can be sent to users
- move api documentation at /api to /docs

**Comment by hunicus** [comment]
At this point, all content is in this PR.

Remaining items:
- fragment linking for faq and api items
- api section layout (a side-nav setup was discussed, but accordion style [which is currently implemented] might be better?)
- should faq be included in docs section for liquid and bisq sites?

**Comment by hunicus** [comment]
Closing this PR since the scope got too big. Opening a new one that just moves API docs from /api to /docs/api.

**Pull request closed without merging**
