### PR TITLE
Get blocks from electrs again

### LINKED ISSUE #4055: Get block data from electrs again
In this commit https://github.com/mempool/mempool/pull/1351/commits/0730053d5d3c1ae66e5b40e888450248123a96eb we reverted to use Core for block data instead of Esplora due to the difficulty bug.

As soon as https://github.com/mempool/electrs/pull/5 is merged, we can revert that change and call getBlock from Esplora again.

### PR DESCRIPTION
**Pull request by mononaut**
Resolves #4055

### CODE REVIEW

**Comment by wiz** [comment]
Will this break romanz/electrs users?

**Review by softsimon — APPROVED** [review]
tested ACK @ [363fc1b00]

**Comment by wiz** [comment]
@softsimon what backends did you test this PR with? none, romanz/electrs, and mempool/electrs ?

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ 363fc1b00bd336618008bfc9fa62cc5a6594f3a2

Screenshot 2023-07-31 at 16 51 59

**Comment by mononaut** [comment]
rebased on master, and fixed the difficulty adjustment bug

**Review by softsimon — CHANGES_REQUESTED** [review]
tested NACK @ [ff76ae1107]

For some reason the historical difficulty adjustments are not indexed with this PR. Not that i am running with `"INDEXING_BLOCKS_AMOUNT": 11000,`. Switching to Master and restart backend it immediately indexes.

If I reindex I get

`Jul 31 21:18:28 [11337] INFO: [Mining] Indexed 0 difficulty adjustments`

**Comment by mononaut** [comment]
should be fixed now - I forgot include `bits` in the db queries 🤦

**Review by softsimon — APPROVED** [review]
tested ACK @ [a863c1740]

**Review by wiz — APPROVED** [review]
Tested ACK @ 8c396978a89b0c4ce8d5f338265c95c539363bde

Definitely faster to get it from electrs rather than core,

**Pull request merged**
