### PR TITLE
Import historical channels

### PR DESCRIPTION
**Pull request by nymkappa**
Depends on https://github.com/mempool/mempool/pull/2331

```mysql
SELECT status, count(*) FROM `channels` GROUP BY status
```

status | count(*)
-- | --
0 | 3485
1 | 78737
2 | 156742

### Testing

* Stop the lightning backend
* `truncate lightning_stats`
* Start the lightning backend with this PR

Example result with ACINQ
Screen Shot 2022-08-17 at 8 19 28 AM

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ v2.5.0-dev [[63ec6e76](https://github.com/mempool/mempool/commit/63ec6e76)]

JSON data structure does not match expected results (edges vs channels, etc.)
also crashes:
```
Aug 18 04:55:31 [12577] DEBUG: <lightning> Reading /mempool/topology/output/topology_1630972800.json.topology
Aug 18 04:55:32 [12577] INFO: <lightning> Founds a topology file that we did not import. Importing historical lightning stats now.
/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:305
            logger_1.default.debug(`${datestr}: Found ${graph.nodes.length} nodes and ${graph.edges.length} channels`);
                                                                                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at LightningStatsImporter.$importHistoricalLightningStats (/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:305:101)
    at async LightningStatsImporter.$run (/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:21:9)

> mempool-backend@2.5.0-dev start-production
> node --max-old-space-size=4096 dist/index.js
```

**Comment by nymkappa** [comment]
Will need to be rebased on https://github.com/mempool/mempool/pull/2319

**Review by wiz — CHANGES_REQUESTED** [review]
Tested NACK @ 64c5f1ce02481580944c7271524257a11a0b05cc

Number of closed channels is not going up
```
root@localhost [mempool_mainnet_lightning]> SELECT status, count(*) FROM `channels` GROUP BY status;
+--------+----------+
| status | count(*) |
+--------+----------+
|      0 |      123 |
|      1 |    81912 |
|      2 |      852 |
+--------+----------+
3 rows in set (0.026 sec)
```

**Review by wiz — APPROVED** [review]
Tested ACK @ 5b9b717a936f21f9d35551526dc03f909651efaa

```
root@localhost [mempool_mainnet_lightning]> SELECT status, count(*) FROM `channels` GROUP BY status;
+--------+----------+
| status | count(*) |
+--------+----------+
|      0 |     3892 |
|      1 |    81858 |
|      2 |   186550 |
+--------+----------+
3 rows in set (0.079 sec)
```

**Pull request merged**
