### PR TITLE
Root frontend network setting

### PR DESCRIPTION
**Pull request by softsimon**
To run a Mempool instance that uses another network as root / use the following setting:

```
  "MAINNET_ENABLED": false,
  "ROOT_NETWORK": "signet",

```

Draft because the dropdown is currently not being hidden if only one non-mainnet network is active.

### CODE REVIEW

**Comment by 1ma** [comment]
These changes succeed at displaying the signet styling in the mainnet URLs (good), but the backend APIs no longer work and pages are not populated with data.

I had to slightly modify my `nginx.conf` and `nginx-mempool.conf` to be able to accommodate other sites alongside mempool. I don't think this is the culprit, but sharing just in case.

/etc/nginx/nginx.conf:
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
}

http {
	# proxy cache
	proxy_cache off;
	proxy_cache_path /var/cache/nginx keys_zone=cache:20m levels=1:2 inactive=600s max_size=500m;
	types_hash_max_size 2048;

	# exempt localhost from rate limit
	geo $limited_ip {
		default		1;
		127.0.0.1	0;
	}

	map $limited_ip $limited_ip_key {
		1 $binary_remote_addr;
		0 '';
	}

	# rate limit requests
	limit_req_zone $limited_ip_key zone=api:5m rate=200r/m;
	limit_req_zone $limited_ip_key zone=electrs:5m rate=2000r/m;
	limit_req_status 429;

	# rate limit connections
	limit_conn_zone $limited_ip_key zone=websocket:10m;
	limit_conn_status 429;

	map $http_accept_language $header_lang {
		default en-US;
		~*^en-US en-US;
		~*^en en-US;
		~*^ar ar;
		~*^cs cs;
		~*^da da;
		~*^de de;
		~*^es es;
		~*^fa fa;
		~*^fr fr;
		~*^ko ko;
		~*^it it;
		~*^he he;
		~*^ka ka;
		~*^hu hu;
		~*^mk mk;
		~*^nl nl;
		~*^ja ja;
		~*^nb nb;
		~*^pl pl;
		~*^pt pt;
		~*^ro ro;
		~*^ru ru;
		~*^sl sl;
		~*^fi fi;
		~*^sv sv;
		~*^th th;
		~*^tr tr;
		~*^uk uk;
		~*^vi vi;
		~*^zh zh;
		~*^hi hi;
		~*^ne ne;
		~*^lt lt;
	}

	map $cookie_lang $lang {
		default $header_lang;
		~*^en-US en-US;
		~*^en en-US;
		~*^ar ar;
		~*^cs cs;
		~*^da da;
		~*^de de;
		~*^es es;
		~*^fa fa;
		~*^fr fr;
		~*^ko ko;
		~*^it it;
		~*^he he;
		~*^ka ka;
		~*^hu hu;
		~*^mk mk;
		~*^nl nl;
		~*^ja ja;
		~*^nb nb;
		~*^pl pl;
		~*^pt pt;
		~*^ro ro;
		~*^ru ru;
		~*^sl sl;
		~*^fi fi;
		~*^sv sv;
		~*^th th;
		~*^tr tr;
		~*^uk uk;
		~*^vi vi;
		~*^zh zh;
		~*^hi hi;
		~*^ne ne;
		~*^lt lt;
	}

	include /etc/nginx/sites-enabled/*.conf;
}

stream {
	ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;
	ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;
	ssl_session_cache shared:STREAM-TLS:1m;
	ssl_session_timeout 4h;
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_prefer_server_ciphers on;
	include /etc/nginx/streams-enabled/*.conf;
}
```

/etc/nginx/sites-enabled/signet-mempool.conf:
```
server {
	listen 10.0.0.1:8008;

	root /var/www/mempool/browser;

	index index.html;

	access_log /var/log/nginx/access_mempool.log;
	error_log /var/log/nginx/error_mempool.log;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;

	server_tokens off;
	server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# reset timed out connections freeing ram
	reset_timedout_connection on;
	# maximum time between packets the client can pause when sending nginx any data
	client_body_timeout 10s;
	# maximum time the client has to send the entire header to nginx
	client_header_timeout 10s;
	# timeout which a single keep-alive client connection will stay open
	keepalive_timeout 69s;
	# maximum time between packets nginx is allowed to pause when sending the client data
	send_timeout 69s;

	# number of requests per connection, does not affect SPDY
	keepalive_requests 1337;

	# enable gzip compression
	gzip on;
	gzip_vary on;
	gzip_comp_level 6;
	gzip_min_length 1000;
	gzip_proxied expired no-cache no-store private auth;
	# text/html is always compressed by gzip module
	gzip_types application/javascript application/json application/ld+json application/manifest+json application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard;

	# limit request body size
	client_max_body_size 10m;

	# enable browser and proxy caching
	add_header Cache-Control "public, no-transform";

	# vary cache if user changes language preference
	add_header Vary Accept-Language;
	add_header Vary Cookie;

	# fallback for all URLs i.e. /address/foo /tx/foo /block/000
	location / {
		try_files /$lang/$uri /$lang/$uri/ $uri $uri/ /en-US/$uri @index-redirect;
		expires 10m;
	}

	location /resources {
		try_files $uri @index-redirect;
		expires 1h;
	}

	# only cache /resources/config.* for 5 minutes since it changes often
	location /resources/config. {
		try_files $uri =404;
		expires 5m;
	}

	location @index-redirect {
		rewrite (.*) /$lang/index.html;
	}

	# location block using regex are matched in order

	# used for cookie override
	location ~ ^/(ar|bg|bs|cs|da|de|et|el|es|eo|eu|fa|fr|gl|ko|hr|id|it|he|ka|lv|lt|hu|mk|ms|nl|ja|nb|nn|pl|pt|pt-BR|ro|ru|sk|sl|sr|sh|fi|sv|th|tr|uk|vi|zh|hi)/ {
		try_files $uri $uri/ /$1/index.html =404;
	}

	# static API docs
	location = /api {
		try_files $uri $uri/ /en-US/index.html =404;
	}

	location = /api/ {
		try_files $uri $uri/ /en-US/index.html =404;
	}

	location /api/v1/ws {
		proxy_pass http://127.0.0.1:18999/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}

	location /api/v1 {
		proxy_pass http://127.0.0.1:18999/api/v1;
	}

	location /api/ {
		proxy_pass http://127.0.0.1:18999/api/v1/;
	}

	# mainnet API
	location /ws {
		proxy_pass http://127.0.0.1:18999/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";
	}
}
```

**Comment by 1ma** [comment]
Sorry, that report was not exactly right. It works on the main dashboard and the block view, but not the transaction view.

OK:
https://sigpool.bitcoinbarcelona.xyz
https://sigpool.bitcoinbarcelona.xyz/block/000002395fae94801e3493d1d4ff5dd16f6a3073e95b8ff99ad36ae47453c8a7

KO (coinbase TX of that block):
https://sigpool.bitcoinbarcelona.xyz/tx/75593f69b58e62b16c23ee566f4d148e140474cb06166a75b489ceae3db968d1

**Comment by softsimon** [comment]
> Sorry, that report was not exactly right.

Try now

**Comment by 1ma** [comment]
Nice, now it works. :+1: Just noticed a minor UI glitch, and is that the block and transaction views are not centered to their position inside the blockchain.

Example (same TX):
mainnet
signet

**Pull request merged**
