### PR TITLE
Enable i18n locale Thai (th)

### PR DESCRIPTION
**Pull request by wiz**
Screen Shot 2021-11-17 at 21 11 32

### CODE REVIEW

**Comment by wiz** [comment]
@Gusb3ll can you review https://mempool.ninja/th/ and tweak the translations as necessary after seeing how they are being used on the live site? also DM me on Twitter @wiz

**Review by softsimon — APPROVED** [review]
tested ACK @ 836f0f06

**Comment by Gusb3ll** [comment]
Alright, will do some tweaking 👍. DMed also

**Comment by Gusb3ll** [comment]
Alright, will do some tweaking 👍

**Pull request merged**
