### PR TITLE
Improve nginx config

### PR DESCRIPTION
**Pull request by erikarvstedt**
Main idea:
Move Docker nginx config to `/nginx/` and reuse some parts of the production config via symlinks.
This setup also makes it easy to share other parts of the production config with Docker in the future.

Test this with:
```bash
# 1. Build Docker image `mempool-tmp`
cd /src/mempool
git clean -xdf # Clean repo. Warning: this deletes untracked files.
./docker/init.sh
docker build -t mempool-tmp frontend

# 2. Run image `mempool-tmp`
cd docker
sed -i  's|mempool/frontend:latest|mempool-tmp|' docker-compose.yml
docker-compose up -d # detached
# Wait a short while until the frontend container has started

## Test frontend
curl localhost
# Test lang-specific redirect
curl -i -H 'Accept-Language: es' localhost
curl -i -H 'Accept-Language: es' localhost/es
curl -s localhost/es/resources/mempool-logo.png | file -

docker-compose kill
docker-compose rm -f
docker rmi mempool-tmp
```

### CODE REVIEW

**Comment by wiz** [comment]
The thing about refactoring the top-level nginx configuration like this is that many downstream projects integrate with our currently simple nginx.conf, so this will likely break those integrations.... so we would need to look into how each of the major RPI distros are doing it and make PRs for those distros as well...

**Comment by erikarvstedt** [comment]
What do you think about keeping `/nginx.conf` and `/nginx-mempool.conf` for backwards compat, deprecating it, and using the new scheme for Docker?

**Comment by erikarvstedt** [comment]
After checking the `full-node distros` in the README, 2 repos would require changes:
- `raspiblitz` requires updating these files:
  - `home.admin/assets/nginx/snippets/mempool.conf`
  - `home.admin/assets/nginx/snippets/mempool-http.conf`
- `embassy-os/mempool-wrapper ` copies the mempool Dockerfiles verbatim, so these must simply by updated.

The rest use `docker-compose` with the prebuilt frontend image.

**Comment by erikarvstedt** [comment]
I've checked the `full-node distros` in the README.

- `embassy-os/mempool-wrapper ` would be broken by this PR because it builds a mempool image with a customized copy of `docker/frontend/Dockerfile`.  Updating the Dockerfile would fix this.

- `raspiblitz` has internal copies of the old nginx config, so it would continue working fine.
   To incorporate this PR, these files must be updated:
    - `home.admin/assets/nginx/snippets/mempool.conf`
    - `home.admin/assets/nginx/snippets/mempool-http.conf`

- The rest use `docker-compose` with the prebuilt frontend image.

**Comment by erikarvstedt** [comment]
Here are the commits that I'll submit as PRs if this branch gets merged:
- [embassy-os/mempool-wrapper](https://github.com/erikarvstedt/mempool-wrapper/commit/2262a2cd18d2e79c3dafc15d3cad1db411b07e87)
- [raspiblitz](https://github.com/erikarvstedt/raspiblitz/commit/0de55d0947f2d7080a0e4b10780da7150417d754)

**Comment by wiz** [comment]
Okay cool, but we'll have to bump this to v2.5.0 because of the downstream changes required. Also instead of "webui" it should just be "static"

**Comment by erikarvstedt** [comment]
Renamed `webui` -> `static`.

**Comment by wiz** [comment]
Here is another issue with this PR that we recently fixed but would be re-introduced by this PR https://github.com/raspibolt/raspibolt/issues/919

**Comment by erikarvstedt** [comment]
I don't see any recent changes to `nginx.conf`. Where's this fix?
```bash 
git fetch --all
git log --all --pretty=format:'%h|%an|%s|%ai|' -5 -- nginx.conf | column -t -s '|'

afb58c59  Erik Arvstedt  Move Docker nginx conf files to `/nginx`                            2022-07-10 13:17:45 +0200  
493dbb1b  wiz            Increase nginx send_timeout and keepalive_requests                  2022-01-27 05:56:38 +0000  
836f0f06  wiz            Enable i18n locale Thai (th)                                        2021-11-17 21:03:35 +0900  
b3e47e14  wiz            Exempt localhost and local networks from rate limits in nginx.conf  2021-10-15 12:32:37 +0900  
07ba2f6e  softsimon      Merge pull request #792 from mempool/i18n/add-macedonian            2021-09-17 13:54:03 +0400  
```
Same for `nginx-mempool.conf`.

**Comment by erikarvstedt** [comment]
Ah, you mean fdb035c0d244de15e512906ea8c3e8227311cf9e (2022-05-18).
This is included in this PR.

**Comment by erikarvstedt** [comment]
You probably mean fdb035c0d244de15e512906ea8c3e8227311cf9e.
This fix is included in this PR. Note that this PR only shares the common parts, i.e. the language mapping and static location config, between Docker and production.

**Comment by wiz** [comment]
True

**Comment by seberm** [comment]
Hello @wiz , what is the status of this PR?

It would be great if we could merge it so we could integrate the mempool.space into nix-bitcoin (https://github.com/fort-nix/nix-bitcoin/pull/505).

Thanks!

**Comment by wiz** [comment]
Closing due to stale, if this is still needed please make a new PR as it's very out of date with master

**Pull request closed without merging**
