### PR TITLE
Add animated css logo.

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
### Description

New concept for animated css logo.

### Expected behaviour

https://user-images.githubusercontent.com/5798170/116329973-df6dfd00-a7a2-11eb-9e03-eecccd2cd20b.mp4

### JS Fiddle

https://jsfiddle.net/miguelmedeiros/7nt8dy6b/4/

### CODE REVIEW

**Comment by AaronDewes** [comment]
Having the logo animated for ever doesn't seem good to me, I'd use this as a loading animation, but I'm very bad at designing, so my feedback probably isn't good.

**Comment by softsimon** [comment]
I don't think we want our logo to be animating and moving. If it was to represent the full mempool it would always be full which is not good either.

**Comment by MiguelMedeiros** [comment]
> Having the logo animated for ever doesn't seem good to me, I'd use this as a loading animation, but I'm very bad at designing, so my feedback probably isn't good.

I think it's a good idea to remove the infinite animation and limit it to reproduce only 2 or 3 cycles.

**Comment by MiguelMedeiros** [comment]
> I don't think we want our logo to be animating and moving. If it was to represent the full mempool it would always be full which is not good either.

The main idea was to simulate that the mempool logo was "alive" (like a living organism, changing all the time).

**Comment by wiz** [comment]
I agree it would be cool to use this for a loading animation, but currently we don't have anything that takes a while to load

**Pull request closed without merging**
