### PR TITLE
use @grpc/grpc-js directly instead of the wrapper lib

### PR DESCRIPTION
**Pull request by antonilol**
This pr replaces the npm package `lightning` with 2 of its dependencies `@grpc/grpc-js` and `@grpc/proto-loader`

interfaces have been rewritten to match LND's grpc output

and...
- i made a utility script that downloads `lightning.proto` from the lnd github repo and generates typescript types from it
that script can be given a specific lnd version or let it auto-detect it from `lnd --version`. usage: `npm run configure-lnd [version]` or `node configure-lnd [version]`
- adds `lightning` as label in package.json, thought it would fit there :)
- noticed admin.macaroon is used by default. this is not needed and only imposes extra security risks. i replaced it with the readonly.macaroon which still allows mempool to read the needed things from lnd

### CODE REVIEW

**Comment by softsimon** [comment]
Downloading the `lightning.proto`-file from github feels like a bit too much added complexity.

**Comment by antonilol** [comment]
> Downloading the `lightning.proto`-file from github feels like a bit too much added complexity.

yeah that's true, i will remove it from the gitignore

the configure script is then only needed for development (compiling without it will generate a fallback type `any`) or if someone wants to be 100% sure for running it with another version of lnd (using a proto file from a different version should generally work but can give random unpredictable errors/bugs sometimes)

**Comment by wiz** [comment]
Removing the lightning npm dep and connecting directly to lightning GRPC is a good idea, but this PR seems to want to do much more than that and feels quite messy - for example, downloading proto from github as part of the build process feels very wrong. Can you just make a new PR that only has the GRPC integration in it, and no other random things mixed in?

**Comment by wiz** [comment]
Why use the GRPC API at all when lnd has a REST API we can use instead?

**Comment by antonilol** [comment]
> Why use the GRPC API at all when lnd has a REST API we can use instead?

good point, made a new pr to use the rest api

**Pull request closed without merging**
