### PR TITLE
Click to close search dropdown

### PR DESCRIPTION
**Pull request by softsimon**
Dropdown will now hide when clicking outside the search result dropdown.

### CODE REVIEW

**Comment by wiz** [comment]
Please rebase onto current master

**Comment by softsimon** [comment]
> Please rebase onto current master

Done

**Comment by wiz** [comment]
Sorry but there are more conflicts :)

**Comment by softsimon** [comment]
> Sorry but there are more conflicts :)

Done

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[cfb4fdb7](https://github.com/mempool/mempool/commit/cfb4fdb7)]

**Pull request merged**
