### PR TITLE
Update mainnet tests

### PR DESCRIPTION
**Pull request by knorrium**
With infinite scrolling, the initial number of blocks loaded was increased and the tests were outdated.

The locators assumed there was only one block with index 0, but we now have an offset, so they had to be included.

Disabled the test that clicks on the "last" block as that is no longer a thing.

### CODE REVIEW

**Comment by wiz** [comment]
It seems the tests still fail? Or is that unrelated?

**Comment by knorrium** [comment]
> It seems the tests still fail? Or is that unrelated?

Mainnet and Bisq are passing, Liquid is still failing due to issue #3052

**Comment by wiz** [comment]
ok will merge master into this PR after 3052 is fixed, and re-test this one, and merge after all green

**Comment by wiz** [comment]
@softsimon did you test this? it modified the frontend code

**Pull request merged**
