### PR TITLE
Moving open/close channels toggle

### PR DESCRIPTION
**Pull request by softsimon**
Had to refactor which component doing the toggling so make sure it works properly

Before
Screen Shot 2022-08-27 at 19 27 28

After
Screen Shot 2022-08-27 at 19 27 21

### CODE REVIEW

**Comment by nymkappa** [comment]
NACK.

This breaks in the following situation:

* Open a new tab
* Open /lightning/node/038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5
* Click on `Closed`, the `Channels` list component title is properly updated, the list is properly updated
* Click on a node in the channel list component, **the `Closed` button is already selected, but the list shows the `Open` channel instead. If you click on `Open` button, the list does not update, because states are out of sync between the list and the toggles**
* It also breaks if you press the "Back" button between two node page for example.

I'm not sure what the PR is aiming to solve anyway because I don't see any bug description or issue linked to that PR.

**Review by nymkappa — CHANGES_REQUESTED** [review]
NACK.

This breaks in the following situation. Note that on `master` branch the following flow works properly.

* Open a new tab
* Open /lightning/node/038fe1bd966b5cb0545963490c631eaa1924e2c4c0ea4e7dcb5d4582a1e7f2f1a5
* Click on `Closed`, the `Channels` list component title is properly updated, the list is properly updated
* Click on a node in the channel list component, **the `Closed` button is already selected, but the list shows the `Open` channel instead. If you click on `Open` button, the list does not update, because states are out of sync between the list and the toggles**
* It also breaks if you press the "Back" button between two node page for example.

I'm not sure what the PR is aiming to solve anyway because I don't see any bug description or issue linked to that PR.

**Comment by nymkappa** [comment]
If https://github.com/mempool/mempool/pull/2437 is preferred, close this PR

**Comment by softsimon** [comment]
Better fixed with https://github.com/mempool/mempool/pull/2437

**Pull request closed without merging**
