### PR TITLE
Syslog is now configurable with minimum priority and facility option.

### LINKED ISSUE #135: Log backend messages to syslog if configured
Add new variable to backend config, something like this
```
"SYSLOG_SOCKET": "127.0.0.1:514" // udp
```

### PR DESCRIPTION
**Pull request by softsimon**
fixes #135

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
NACK - tested on mempool.ninja using default configuration (no syslog block at all), but the syslog daemon still receives `debug` level messages instead of the default minimum priority of `info`

**Comment by softsimon** [comment]
Please try again :)

**Review by wiz — APPROVED** [review]
ACK - tested OK on mempool.ninja using various configurations

**Comment by wiz** [comment]
Thanks for fixing this :heart:

**Pull request merged**
