### PR TITLE
Adjust block preview layout

### PR DESCRIPTION
**Pull request by mononaut**
Adjusts the block preview layout to make the block hash more prominent

| before | after |
|-|-|
| hash-before | hash-after |

### CODE REVIEW

**Review by softsimon — APPROVED** [review]
utACK

**Comment by wiz** [comment]
How does this look on Liquid with 7 digit block hashes or how high can we go?

**Comment by mononaut** [comment]
good point, the rightmost digits were clipped awkwardly at higher block heights.

I just pushed a change to truncate dynamically in CSS instead, which should also use the space better at lower block heights. It means we gain an ellipsis on the top line, and lose perfect character alignment

| liquid-block | bitcoin-short-block |
|-|-|

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.5.0-dev [[deae7b28](https://github.com/mempool/mempool/commit/deae7b28)]

Looks good but there seems to be extra space where the block hash used to be, below the block height / above the table rows, maybe we should move that up a little? Also, currently lightning node pubkeys are blue, should the block hash also be blue or should we change the lightning pubkey to be white? I think the blue looks cool for a pubkey/hash, @softsimon wdyt?

**Pull request merged**
