### PR TITLE
Fix missing tx column in main dashboard on mobile

### PR DESCRIPTION
**Pull request by nymkappa**
Fixes https://github.com/mempool/mempool/issues/1704

### CODE REVIEW

**Comment by wiz** [comment]
Tested but I don't see any change in behavior from prod.
Maybe @knorrium can verify this fix does anything?

Screen Shot 2022-05-25 at 17 26 00
Screen Shot 2022-05-25 at 17 25 20

**Comment by nymkappa** [comment]
@wiz This must have break with a recent change because I don't see it in prod as well. But on `master` branch you can see the last column disappear if you set your screen width to 375 or lower.

**Comment by wiz** [comment]
Sorry, disregard previous comment, need to re-test

**Review by wiz — APPROVED** [review]
Tested ACK @ v2.4.0-dev [[c16c7ee0](https://github.com/mempool/mempool/commit/c16c7ee0)]

### Before
Screen Shot 2022-05-25 at 18 16 44

### After
Screen Shot 2022-05-25 at 18 16 51

**Pull request merged**
