### PR TITLE
UI/UX: make human readable x-Axis date labels.

### LINKED ISSUE #899: Human readable x-Axis date labels.
### Description
Make echarts human readable x-Axis date labels.

### Expected Behaviour
2 hours chart: **15 mins interval**
2h-span

24 hours chart: **2 hours interval**
24h-span

1 week chart: **1 day interval**
1w-span

1 month chart: **1 week interval**
1m-span

3 months chart: **1 week interval**
3m-span

6 months chart: **1 month interval**
6m-span

1 year chart: **1 month interval**
1y-span

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
Fix #899.

### CODE REVIEW

**Review by wiz — CHANGES_REQUESTED** [review]
Tested f5bd9cc9 and using the new angular localized timestamps look good - however, I found the following issues:

* This PR should fix issue #842, but for some reason you created a new issue #899 with the exact same title which is very strange and confusing. To be clear, this PR should fix #842 which for the avoidance of doubt includes aligning the labels with the axis on midnight which requires forking the chart library as we discussed.

* The new `getAxisLabelInterval()` method added in this PR doesn't seem to take the width of the window into account at all, and just returns a static number. This won't work for smaller window sizes since the labels will get squished together, and it doesn't look good on large window sizes since the labels will become too far apart. I think the default implementation of this method takes the width into account and determines what can reasonably fit - not sure why it's necessary to override it, but if it is necessary to re-implement this method then the same size width evaluation needs to be added.

* This PR seems to change the font style and layout of the mouseover tooltip legend, which if intentional should probably be in a separate PR.... unless I am missing something, I don't see how the x-axis labels are related to the mouseover legend.

**Comment by MiguelMedeiros** [comment]
Hey @wiz, thanks for the feedback!

I've managed to make it work with our forked npm packages :partying_face: : 
- **mempool/echarts** 
- **mempool/npx-echarts**.

I got stuck a little on the mobile screen, but now I think I've got a way to deal with the xAxis labels when you resize the screen, so they don´t get clustered.

I need a little more time, though! I will send this PR tomorrow morning.

**Comment by wiz** [comment]
Okay cool, can't wait to see it - btw on the 1Y chart I see this issue, looks like it's not getting aligned properly on months with 31 days?
Screen Shot 2021-11-20 at 7 16 36

**Comment by MiguelMedeiros** [comment]
I will close this one.

Opened a new PR: https://github.com/mempool/mempool/pull/946

**Pull request closed without merging**
