### PR TITLE
New API docummentation.

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
New API documentation.

### CODE REVIEW

**Comment by MiguelMedeiros** [comment]
Fix #461

**Comment by wiz** [comment]
Great work, I like the syntax highlighting but I don't think it's worth adding a new npm dep for that - if we want to do syntax highlighting probably best to just make our own CSS and not add a new dependency

**Comment by MiguelMedeiros** [comment]
> Great work, I like the syntax highlighting but I don't think it's worth adding a new npm dep for that - if we want to do syntax highlighting probably best to just make our own CSS and not add a new dependency

Ok, done!

- [x] Removed the highlight.js dependency.
- [x] Made our own styles for `code-template-component`.

**Review by softsimon — APPROVED** [review]
I approve 👍

**Pull request merged**
