### PR TITLE
simple acceleration mode on main tx page

### PR DESCRIPTION
**Pull request by mononaut**
_(PR onto #5218 branch)_

refactors the accelerate checkout slightly, and integrates it into the main tx page for non-logged-in users.

Screenshot 2024-06-27 at 2 03 56 AM

the `/tracker` page implementation should be unchanged.

### CODE REVIEW

**Comment by nymkappa** [comment]
Following comments are just UI/UX feedback. The integration itself works fine 👍🏻.

I think in that case, if the user click on the `Accelerate` button, we might not need to show the `Wait` option?

Or should selecting the `Wait` option close the modal on desktop only maybe?

Another suggestion would be to select the `Accelerate` option by default, again because the user already suggested he wants to accelerate by clicking on the `Accelerate` button in the transaction summary box.

Need to re-center the payment options as well _(I currently use flex justify around)_

image

**Comment by mononaut** [comment]
> I think in that case, if the user click on the Accelerate button, we might not need to show the Wait option? Or should selecting the Wait option close the modal on desktop only maybe?

I think we still want to show that explicit choice with the pricing & timing info before moving on to the payment step, but we can iterate on this later.

> Another suggestion would be to select the Accelerate option by default, again because the user already suggested he wants to accelerate by clicking on the Accelerate button in the transaction summary box.

probably yes, but on the other hand maybe that defeats the point of making the user "opt in" with the radio button.

**Comment by mononaut** [comment]
> Need to re-center the payment options as well (I currently use flex justify around)

I just pushed up a fix for this, alongside some other small UI changes:

https://github.com/mempool/mempool/assets/83316221/ce3abcf5-cbc4-4688-b991-87aba925893e

**Comment by nymkappa** [comment]
> probably yes, but on the other hand maybe that defeats the point of making the user "opt in" with the radio button.

Well the user still have to actively click on the `Accelerate` button, alongside selecting a payment method and actually make the payment. I think that's enough "opt in" steps already.

> but we can iterate on this later

but yeah same vibe for my comment above 👍🏻

**Comment by wiz** [comment]
Replaced by #5233

**Pull request closed without merging**
