### PR TITLE
Update production configurations + README for v2.3

### PR DESCRIPTION
**Pull request by wiz**
@Emzy @devinbileck please test the newly refactored nginx configuration files for your setup - note you will need 3 separate hostnames for the 3 sites if you support them all, i.e. we use mempool.space / bisq.markets / liquid.network

### CODE REVIEW

**Review by softsimon — APPROVED** [review]
utACK

**Review by Emzy — COMMENTED** [review]
tested ack 
(only mainnet, testnet and signet)

**Comment by wiz** [comment]
@emzy thanks a lot for testing and reviewing - would you mind doing PR for those changes and any other improvements to the production README you think would be helpful?

**Comment by devinbileck** [comment]
Tested ACK
I am only running mainnet and bisq and successfully upgraded mempool.bisq.services to 2.3.0-rc5.

**Pull request merged**
