### PR TITLE
Handling for network interruptions in scrollable blockchain

### LINKED ISSUE #2983: Offline blockchain placeholder missing when scrolled away
The skeleton loader / placeholder is missing when offline mode, if scrolled past first blocks. Example:

Screenshot 2023-01-27 at 15 48 26

### PR DESCRIPTION
**Pull request by mononaut**
This PR improves how the scrollable blockchain component handles network interruptions:
 - Extends the loading skeleton/placeholder to the end of the scrollable area when loading the page in offline mode (fixes #2983).
 - Reloads missing blocks as soon as connection is restored.

### CODE REVIEW

**Review by softsimon — CHANGES_REQUESTED** [review]
If I scroll the blockchain, and then kill the backend, only the first 8 blocks become skeleton loaders 

Screenshot 2023-02-14 at 13 22 51

**Comment by mononaut** [comment]
Fixed and rebased.

Now every block becomes a skeleton loader in offline mode.

**Review by softsimon — CHANGES_REQUESTED** [review]
Works better now, but there is a gap in the skeleton every 8 or 16 blocks.

Screenshot 2023-02-15 at 10 51 29

**Comment by mononaut** [comment]
the gaps should be fixed now

**Review by softsimon — APPROVED** [review]
tested ACK @ v2.5.0-dev [[c65674479](https://github.com/mempool/mempool/commit/c65674479)]

**Pull request merged**
